/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";
import type { BodyType, ErrorType } from "../../libs/customAxios";
import { customInstance } from "../../libs/customAxios";
import type {
	CreateCommunityPost201AllOf,
	CreateCommunityPostPayloadDto,
	GetCommunityPosts200AllOf,
	GetCommunityPostsParams,
} from ".././model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 현재 Space 기준 커뮤니티 게시글 목록을 조회합니다.
 * @summary 커뮤니티 게시글 목록 조회
 */
export const getCommunityPosts = (
	params?: GetCommunityPostsParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<GetCommunityPosts200AllOf>(
		{ url: `/api/v1/community/posts`, method: "GET", params, signal },
		options,
	);
};

export const getGetCommunityPostsQueryKey = (
	params?: GetCommunityPostsParams,
) => {
	return [`/api/v1/community/posts`, ...(params ? [params] : [])] as const;
};

export const getGetCommunityPostsQueryOptions = <
	TData = Awaited<ReturnType<typeof getCommunityPosts>>,
	TError = ErrorType<void>,
>(
	params?: GetCommunityPostsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCommunityPosts>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};
	const queryKey = queryOptions?.queryKey ?? getGetCommunityPostsQueryKey(params);
	const queryFn: QueryFunction<Awaited<ReturnType<typeof getCommunityPosts>>> = ({
		signal,
	}) => getCommunityPosts(params, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getCommunityPosts>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCommunityPostsQueryResult = NonNullable<
	Awaited<ReturnType<typeof getCommunityPosts>>
>;
export type GetCommunityPostsQueryError = ErrorType<void>;

export function useGetCommunityPosts<
	TData = Awaited<ReturnType<typeof getCommunityPosts>>,
	TError = ErrorType<void>,
>(
	params: undefined | GetCommunityPostsParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCommunityPosts>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getCommunityPosts>>,
					TError,
					Awaited<ReturnType<typeof getCommunityPosts>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCommunityPosts<
	TData = Awaited<ReturnType<typeof getCommunityPosts>>,
	TError = ErrorType<void>,
>(
	params?: GetCommunityPostsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCommunityPosts>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getCommunityPosts>>,
					TError,
					Awaited<ReturnType<typeof getCommunityPosts>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCommunityPosts<
	TData = Awaited<ReturnType<typeof getCommunityPosts>>,
	TError = ErrorType<void>,
>(
	params?: GetCommunityPostsParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getCommunityPosts>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetCommunityPostsQueryOptions(params, options);
	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * 현재 Space 기준 커뮤니티 게시글을 작성합니다.
 * @summary 커뮤니티 게시글 작성
 */
export const createCommunityPost = (
	createCommunityPostPayloadDto: BodyType<CreateCommunityPostPayloadDto>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CreateCommunityPost201AllOf>(
		{
			url: `/api/v1/community/posts`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createCommunityPostPayloadDto,
			signal,
		},
		options,
	);
};

export const getCreateCommunityPostMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createCommunityPost>>,
		TError,
		{ data: BodyType<CreateCommunityPostPayloadDto> },
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createCommunityPost>>,
	TError,
	{ data: BodyType<CreateCommunityPostPayloadDto> },
	TContext
> => {
	const mutationKey = ["createCommunityPost"];
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };
	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createCommunityPost>>,
		{ data: BodyType<CreateCommunityPostPayloadDto> }
	> = (props) => {
		const { data } = props ?? {};

		return createCommunityPost(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateCommunityPostMutationResult = NonNullable<
	Awaited<ReturnType<typeof createCommunityPost>>
>;
export type CreateCommunityPostMutationBody =
	BodyType<CreateCommunityPostPayloadDto>;
export type CreateCommunityPostMutationError = ErrorType<void>;

/**
 * @summary 커뮤니티 게시글 작성
 */
export const useCreateCommunityPost = <
	TError = ErrorType<void>,
	TContext = unknown,
>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createCommunityPost>>,
			TError,
			{ data: BodyType<CreateCommunityPostPayloadDto> },
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createCommunityPost>>,
	TError,
	{ data: BodyType<CreateCommunityPostPayloadDto> },
	TContext
> => {
	const mutationOptions = getCreateCommunityPostMutationOptions(options);

	return useMutation(mutationOptions, queryClient);
};
