import {
  ADMIN_AUTH_LOGIN_PATH,
  ADMIN_AUTH_PATH,
  ADMIN_MAIN_PATH,
  BOTTOM_TAB_APP_PATH,
  BOTTOM_TAB_RESERVATION_PATH,
  CATEGORIES_PATH,
  CATEGORY_EDIT_PATH,
  CATEGORY_PATH,
  DEPOT_FILE_SERVICE_CATEGORIES_PATH,
  DEPOT_FILE_SERVICE_CATEGORY_EDIT_PATH,
  DEPOT_FILE_SERVICE_CATEGORY_PATH,
  DEPOT_FILE_SERVICE_FILE_EDIT_PATH,
  DEPOT_FILE_SERVICE_FILE_PATH,
  DEPOT_FILE_SERVICE_FILES_PATH,
  DEPOT_FILE_SERVICE_GROUP_EDIT_PATH,
  DEPOT_FILE_SERVICE_GROUP_PATH,
  DEPOT_FILE_SERVICE_GROUPS_PATH,
  DEPOT_FILE_SERVICE_PATH,
  FACE_ANALYSIS_PATH,
  FACE_ANALYSES_PATH,
  FACE_ANALYSIS_DETAIL_PATH,
  FACE_ANALYSIS_UPLOAD_PATH,
  FACE_ANALYSIS_STATS_PATH,
  GROUP_EDIT_PATH,
  GROUP_PATH,
  GROUPS_PATH,
  POST_SERVICE_CATEGORIES_PATH,
  POST_SERVICE_CATEGORY_EDIT_PATH,
  POST_SERVICE_CATEGORY_PATH,
  POST_SERVICE_GROUP_EDIT_PATH,
  POST_SERVICE_GROUP_PATH,
  POST_SERVICE_GROUPS_PATH,
  POST_SERVICE_PATH,
  POST_SERVICE_POST_EDIT_PATH,
  POST_SERVICE_POST_PATH,
  POST_SERVICE_POSTS_PATH,
  RESERVATION_EDIT_PATH,
  RESERVATION_PATH,
  RESERVATIONS_PATH,
  SERVICE_EDIT_PATH,
  SERVICE_PATH,
  SERVICES_PATH,
  SESSION_EDIT_PATH,
  SESSION_PATH,
  SESSIONS_PATH,
  SPACE_EDIT_PATH,
  SPACE_PATH,
  SPACE_SERVICE_CATEGORIES_PATH,
  SPACE_SERVICE_CATEGORY_EDIT_PATH,
  SPACE_SERVICE_CATEGORY_PATH,
  SPACE_SERVICE_GROUP_EDIT_PATH,
  SPACE_SERVICE_GROUP_PATH,
  SPACE_SERVICE_GROUPS_PATH,
  SPACE_SERVICE_PATH,
  SPACE_SERVICE_SPACE_EDIT_PATH,
  SPACE_SERVICE_SPACE_PATH,
  SPACE_SERVICE_SPACES_PATH,
  SPACES_PATH,
  TEMPLATE_EDIT_PATH,
  TEMPLATE_PATH,
  TEMPLATES_PATH,
  TIMELINE_ITEM_EDIT_PATH,
  TIMELINE_ITEM_PATH,
  TIMELINE_ITEMS_PATH,
  USER_EDIT_PATH,
  USER_PATH,
  USER_SERVICE_CATEGORIES_PATH,
  USER_SERVICE_CATEGORY_EDIT_PATH,
  USER_SERVICE_CATEGORY_PATH,
  USER_SERVICE_GROUP_EDIT_PATH,
  USER_SERVICE_GROUP_PATH,
  USER_SERVICE_GROUPS_PATH,
  USER_SERVICE_PATH,
  USER_SERVICE_USER_EDIT_PATH,
  USER_SERVICE_USER_PATH,
  USER_SERVICE_USERS_PATH,
  USERS_PATH,
} from '@shared/vars';

export type Paths =
  | typeof POST_SERVICE_PATH
  | typeof POST_SERVICE_POSTS_PATH
  | typeof POST_SERVICE_POST_PATH
  | typeof POST_SERVICE_POST_EDIT_PATH
  | typeof POST_SERVICE_GROUPS_PATH
  | typeof POST_SERVICE_GROUP_PATH
  | typeof POST_SERVICE_GROUP_EDIT_PATH
  | typeof POST_SERVICE_CATEGORIES_PATH
  | typeof POST_SERVICE_CATEGORY_PATH
  | typeof POST_SERVICE_CATEGORY_EDIT_PATH
  | typeof DEPOT_FILE_SERVICE_PATH
  | typeof DEPOT_FILE_SERVICE_FILES_PATH
  | typeof DEPOT_FILE_SERVICE_FILE_PATH
  | typeof DEPOT_FILE_SERVICE_FILE_EDIT_PATH
  | typeof DEPOT_FILE_SERVICE_GROUPS_PATH
  | typeof DEPOT_FILE_SERVICE_GROUP_PATH
  | typeof DEPOT_FILE_SERVICE_GROUP_EDIT_PATH
  | typeof DEPOT_FILE_SERVICE_CATEGORIES_PATH
  | typeof DEPOT_FILE_SERVICE_CATEGORY_PATH
  | typeof DEPOT_FILE_SERVICE_CATEGORY_EDIT_PATH
  | typeof SPACE_SERVICE_PATH
  | typeof SPACE_SERVICE_SPACES_PATH
  | typeof SPACE_SERVICE_SPACE_PATH
  | typeof SPACE_SERVICE_SPACE_EDIT_PATH
  | typeof SPACE_SERVICE_GROUPS_PATH
  | typeof SPACE_SERVICE_GROUP_PATH
  | typeof SPACE_SERVICE_GROUP_EDIT_PATH
  | typeof SPACE_SERVICE_CATEGORIES_PATH
  | typeof SPACE_SERVICE_CATEGORY_PATH
  | typeof SPACE_SERVICE_CATEGORY_EDIT_PATH
  | typeof USER_SERVICE_PATH
  | typeof USER_SERVICE_USERS_PATH
  | typeof USER_SERVICE_USER_PATH
  | typeof USER_SERVICE_USER_EDIT_PATH
  | typeof USER_SERVICE_GROUPS_PATH
  | typeof USER_SERVICE_GROUP_PATH
  | typeof USER_SERVICE_GROUP_EDIT_PATH
  | typeof USER_SERVICE_CATEGORIES_PATH
  | typeof USER_SERVICE_CATEGORY_PATH
  | typeof USER_SERVICE_CATEGORY_EDIT_PATH
  | typeof CATEGORIES_PATH
  | typeof CATEGORY_PATH
  | typeof CATEGORY_EDIT_PATH
  | typeof GROUPS_PATH
  | typeof GROUP_PATH
  | typeof GROUP_EDIT_PATH
  // 서비스
  | typeof BOTTOM_TAB_APP_PATH
  | typeof BOTTOM_TAB_RESERVATION_PATH
  | typeof SERVICE_PATH
  | typeof SERVICES_PATH
  | typeof SERVICE_EDIT_PATH
  | typeof ADMIN_MAIN_PATH
  | typeof ADMIN_AUTH_PATH
  | typeof ADMIN_AUTH_LOGIN_PATH
  // 그룹
  | typeof GROUPS_PATH
  | typeof GROUP_PATH
  | typeof GROUP_EDIT_PATH
  // 이용자
  | typeof USERS_PATH
  | typeof USER_PATH
  | typeof USER_EDIT_PATH
  // 카테고리
  | typeof CATEGORIES_PATH
  | typeof CATEGORY_PATH
  | typeof CATEGORY_EDIT_PATH
  // 매장
  | typeof SPACES_PATH
  | typeof SPACE_PATH
  | typeof SPACE_EDIT_PATH
  // 세션
  | typeof SESSIONS_PATH
  | typeof SESSION_PATH
  | typeof SESSION_EDIT_PATH
  // 타임라인
  | typeof TIMELINE_ITEMS_PATH
  | typeof TIMELINE_ITEM_PATH
  | typeof TIMELINE_ITEM_EDIT_PATH
  // 예약
  | typeof RESERVATIONS_PATH
  | typeof RESERVATION_PATH
  | typeof RESERVATION_EDIT_PATH
  // 템플릿
  | typeof TEMPLATES_PATH
  | typeof TEMPLATE_PATH
  | typeof TEMPLATE_EDIT_PATH
  // 외모 분석
  | typeof FACE_ANALYSIS_PATH
  | typeof FACE_ANALYSES_PATH
  | typeof FACE_ANALYSIS_DETAIL_PATH
  | typeof FACE_ANALYSIS_UPLOAD_PATH
  | typeof FACE_ANALYSIS_STATS_PATH;
