FROM node:24-alpine AS base

ARG PNPM_VERSION=10.16.0
ENV PNPM_HOME=/usr/local/bin

RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate
RUN apk add --update --no-cache libc6-compat && rm -rf /var/cache/apk/*
RUN pnpm add -g turbo

WORKDIR /app

FROM base AS setup

COPY . .
RUN turbo prune --scope=idp-web --docker

FROM base AS builder

WORKDIR /app
COPY --from=setup /app/out/full/ ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install
COPY turbo.json turbo.json
RUN find apps/idp/web/src -name '*.e2e.ts' -delete
ENV NEXT_IGNORE_BUILD_ERRORS=true
RUN pnpm --filter idp-web build

FROM node:24-alpine AS runner

WORKDIR /app

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

COPY --from=builder --chown=nextjs:nodejs /app/apps/idp/web/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/idp/web/.next/static ./apps/idp/web/.next/static

ENV NODE_ENV=production
ENV PORT=3008
ENV HOSTNAME=0.0.0.0

USER nextjs

EXPOSE 3008

CMD ["node", "apps/idp/web/server.js"]
