ARG NODE_BASE_IMAGE=docker.io/library/node:24-alpine
ARG NGINX_BASE_IMAGE=docker.io/library/nginx:1.27-alpine

FROM ${NODE_BASE_IMAGE} AS base

ARG PNPM_VERSION=10.16.0
ARG TURBO_VERSION=2.8.14
ENV PNPM_HOME=/usr/local/bin
ENV PNPM_STORE_DIR=/pnpm/store

RUN corepack enable && corepack prepare pnpm@${PNPM_VERSION} --activate
RUN apk add --update --no-cache libc6-compat && rm -rf /var/cache/apk/*
RUN pnpm add -g turbo@${TURBO_VERSION}

WORKDIR /app

FROM base AS setup

COPY . .
RUN turbo prune --scope=tool-storybook --docker

FROM base AS builder

WORKDIR /app
COPY --from=setup /app/out/json/ ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --store-dir /pnpm/store --no-frozen-lockfile --prefer-offline
COPY --from=setup /app/out/full/ ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store \
    --mount=type=cache,id=turbo,target=/app/.turbo \
    pnpm exec turbo build --filter=tool-storybook...

FROM ${NGINX_BASE_IMAGE} AS runner

COPY devops/nginx.tool-storybook.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/apps/tool/storybook/storybook-static /usr/share/nginx/html

EXPOSE 3009

CMD ["nginx", "-g", "daemon off;"]
