server {
    listen 3009;
    server_name _;
    root /usr/share/nginx/html;

    location = /storybook {
        return 301 /storybook/;
    }

    location /storybook/ {
        rewrite ^/storybook/(.*)$ /$1 break;
        try_files $uri /index.html;
    }

    location / {
        return 404;
    }
}
