/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OIDC Identity Provider
 * OpenID Connect Identity Provider API

OIDC 인증 및 IDP 관리 API를 제공합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */

export type CategoryTypes = (typeof CategoryTypes)[keyof typeof CategoryTypes];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryTypes = {
	Role: "Role",
	Space: "Space",
	File: "File",
	User: "User",
} as const;
