/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OIDC Identity Provider
 * OpenID Connect Identity Provider API
 * OpenAPI spec version: 1.0.0
 */

export interface LoginErrorDto {
  /** 에러 코드 */
  error: string;
  /** 남은 시도 횟수 */
  remainingAttempts?: number;
  /** 잠금 해제 시간 (ISO 8601) */
  lockedUntil?: string;
  /** 임시 잠금 임계값 */
  temporaryLockThreshold?: number;
  /** 임시 잠금 시간 (분) */
  temporaryLockDurationMin?: number;
}
