/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OIDC Identity Provider
 * OpenID Connect Identity Provider API
 * OpenAPI spec version: 1.0.0
 */

export interface TokenValidationDto {
  /** 토큰 유효 여부 */
  valid: boolean;
  /** 이메일 주소 */
  email?: string;
  /** 유효하지 않은 이유 */
  reason?: string;
}
