import {
  CATEGORIES_PAGE_PATH,
  CATEGORY_EDIT_PAGE_PATH,
  CATEGORY_ITEMS_PAGE_PATH,
  CATEGORY_ITEM_EDIT_PAGE_PATH,
  CATEGORY_PAGE_PATH,
  GROUPS_PAGE_PATH,
  GROUP_EDIT_PAGE_PATH,
  GROUP_PAGE_PATH,
  LOGIN_PAGE_PATH,
  SERVICES_PAGE_PATH,
  SERVICE_EDIT_PAGE_PATH,
  SERVICE_PAGE_PATH,
  USERS_PAGE_PATH,
  USER_EDIT_PAGE_PATH,
  USER_PAGE_PATH,
  SPACES_PAGE_PATH,
  SPACE_EDIT_PAGE_PATH,
  SPACE_PAGE_PATH,
  ROLE_EDIT_PAGE_PATH,
  ROLES_PAGE_PATH,
  ROLE_PAGE_PATH,
  SESSIONS_PAGE_PATH,
  SESSION_PAGE_PATH,
  SESSION_EDIT_PAGE_PATH,
  TIMELINES_PAGE_PATH,
  TIMELINE_EDIT_PAGE_PATH,
  TIMELINE_PAGE_PATH,
  TIMELINEITEMS_PAGE_PATH,
  TIMELINEITEM_EDIT_PAGE_PATH,
  TIMELINEITEM_PAGE_PATH,
} from '@constants';

export const ADMIN_PATH = '/admin' as const;
export const DASHBOARD_PAGE_PATH = `${ADMIN_PATH}/dashboard` as const;
export const ADMIN_AUTH_PATH = `${ADMIN_PATH}/auth` as const;
export const ADMIN_AUTH_LOGIN_PATH = `${ADMIN_AUTH_PATH}/login` as const;
export const ADMIN_AUTH_SERVICE_PATH = `${ADMIN_AUTH_PATH}/service` as const;
export const ADMIN_AUTH_SERVICE_CATEGORIES_PATH =
  `${ADMIN_AUTH_SERVICE_PATH}/categories` as const;
export type Paths =
  | typeof DASHBOARD_PAGE_PATH
  | typeof ADMIN_AUTH_PATH
  | typeof ADMIN_AUTH_LOGIN_PATH
  | typeof ADMIN_AUTH_SERVICE_PATH
  | typeof ADMIN_AUTH_SERVICE_CATEGORIES_PATH;
