module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  rootDir: "./src",
  testMatch: ["**/*.test.ts"],
  moduleFileExtensions: ["ts", "js", "json"],
  moduleNameMapper: {
    "^@shared/schema$": "<rootDir>/../../../packages/shared-schema/src",
    "^@shared/types$": "<rootDir>/../../../packages/shared-types/src", 
    "^@shared/utils$": "<rootDir>/../../../packages/shared-utils/src",
    "^@shared/vars$": "<rootDir>/../../../packages/shared-vars/src",
    "^@shared/meta$": "<rootDir>/../../../packages/shared-meta/src",
    "^@shared$": "<rootDir>/../../../packages/shared-schema/src",
    "^@shared/(.*)$": "<rootDir>/shared/$1",
  },
  transform: {
    "^.+\\.ts$": [
      "ts-jest",
      {
        tsconfig: {
          module: "commonjs",
          target: "es2022",
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
          experimentalDecorators: true,
          emitDecoratorMetadata: true,
          types: ["jest", "node"],
          skipLibCheck: true,
          strict: false,
          paths: {
            "@shared": ["./shared/index"],
            "@shared/*": ["./shared/*"],
            "@shared/types": ["../../packages/shared-types/src"],
            "@shared/schema": ["../../packages/shared-schema/src"],
            "@shared/utils": ["../../packages/shared-utils/src"],
            "@shared/vars": ["../../packages/shared-vars/src"],
          },
        },
      },
    ],
  },
  maxWorkers: 1,
  testTimeout: 5000,
  forceExit: true,
  detectOpenHandles: true,
};
