/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { Order } from './order';

export type GetGroupsByQueryParams = {
/**
 * 건너뛸 항목 수 (페이징)
 */
skip?: number;
/**
 * 가져올 항목 수 (페이징)
 */
take?: number;
name?: string;
serviceId?: string;
orderByCreatedAt?: Order;
};
