/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateGymDto {
  name?: string;
  label?: string;
  businessNo?: string;
  address?: string;
  phone?: string;
  email?: string;
}
