/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OIDC Identity Provider
 * OpenID Connect Identity Provider API

OIDC 인증 및 IDP 관리 API를 제공합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetSecurityPolicy200AllOf,
  UpdateSecurityPolicy200AllOf,
  UpdateSecurityPolicyDto
} from '.././model';

import { customIdpInstance } from '../../libs/customIdpAxios';
import type { ErrorType , BodyType } from '../../libs/customIdpAxios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 현재 시스템 보안 정책을 조회합니다.
 * @summary 보안 정책 조회
 */
export const getSecurityPolicy = (
    
 options?: SecondParameter<typeof customIdpInstance>,signal?: AbortSignal
) => {
      
      
      return customIdpInstance<GetSecurityPolicy200AllOf>(
      {url: `/api/v1/idp/security-policy`, method: 'GET', signal
    },
      options);
    }
  



export const getGetSecurityPolicyQueryKey = () => {
    return [
    `/api/v1/idp/security-policy`
    ] as const;
    }

    
export const getGetSecurityPolicyQueryOptions = <TData = Awaited<ReturnType<typeof getSecurityPolicy>>, TError = ErrorType<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecurityPolicy>>, TError, TData>>, request?: SecondParameter<typeof customIdpInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSecurityPolicyQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSecurityPolicy>>> = ({ signal }) => getSecurityPolicy(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSecurityPolicy>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSecurityPolicyQueryResult = NonNullable<Awaited<ReturnType<typeof getSecurityPolicy>>>
export type GetSecurityPolicyQueryError = ErrorType<void>


export function useGetSecurityPolicy<TData = Awaited<ReturnType<typeof getSecurityPolicy>>, TError = ErrorType<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecurityPolicy>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSecurityPolicy>>,
          TError,
          Awaited<ReturnType<typeof getSecurityPolicy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customIdpInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSecurityPolicy<TData = Awaited<ReturnType<typeof getSecurityPolicy>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecurityPolicy>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSecurityPolicy>>,
          TError,
          Awaited<ReturnType<typeof getSecurityPolicy>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customIdpInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSecurityPolicy<TData = Awaited<ReturnType<typeof getSecurityPolicy>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecurityPolicy>>, TError, TData>>, request?: SecondParameter<typeof customIdpInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 보안 정책 조회
 */

export function useGetSecurityPolicy<TData = Awaited<ReturnType<typeof getSecurityPolicy>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecurityPolicy>>, TError, TData>>, request?: SecondParameter<typeof customIdpInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSecurityPolicyQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary 보안 정책 조회
 */
export const prefetchGetSecurityPolicyQuery = async <TData = Awaited<ReturnType<typeof getSecurityPolicy>>, TError = ErrorType<void>>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSecurityPolicy>>, TError, TData>>, request?: SecondParameter<typeof customIdpInstance>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetSecurityPolicyQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * 시스템 보안 정책을 수정합니다. 변경할 필드만 전달합니다.
 * @summary 보안 정책 수정
 */
export const updateSecurityPolicy = (
    updateSecurityPolicyDto: BodyType<UpdateSecurityPolicyDto>,
 options?: SecondParameter<typeof customIdpInstance>,) => {
      
      
      return customIdpInstance<UpdateSecurityPolicy200AllOf>(
      {url: `/api/v1/idp/security-policy`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateSecurityPolicyDto
    },
      options);
    }
  


export const getUpdateSecurityPolicyMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSecurityPolicy>>, TError,{data: BodyType<UpdateSecurityPolicyDto>}, TContext>, request?: SecondParameter<typeof customIdpInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSecurityPolicy>>, TError,{data: BodyType<UpdateSecurityPolicyDto>}, TContext> => {

const mutationKey = ['updateSecurityPolicy'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSecurityPolicy>>, {data: BodyType<UpdateSecurityPolicyDto>}> = (props) => {
          const {data} = props ?? {};

          return  updateSecurityPolicy(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSecurityPolicyMutationResult = NonNullable<Awaited<ReturnType<typeof updateSecurityPolicy>>>
    export type UpdateSecurityPolicyMutationBody = BodyType<UpdateSecurityPolicyDto>
    export type UpdateSecurityPolicyMutationError = ErrorType<void>

    /**
 * @summary 보안 정책 수정
 */
export const useUpdateSecurityPolicy = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSecurityPolicy>>, TError,{data: BodyType<UpdateSecurityPolicyDto>}, TContext>, request?: SecondParameter<typeof customIdpInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSecurityPolicy>>,
        TError,
        {data: BodyType<UpdateSecurityPolicyDto>},
        TContext
      > => {

      const mutationOptions = getUpdateSecurityPolicyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    