/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Plate
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import type { AlbumDto } from './albumDto';
import type { AssetDto } from './assetDto';

export interface AlbumEntryDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  /** 소속 Space ID */
  spaceId: string;
  /** 앨범 ID */
  albumId: string;
  /** 에셋 ID */
  assetId: string;
  /** 표시 순서 */
  position: number;
  /**
   * 캡션
   * @nullable
   */
  caption?: string | null;
  /** 소속 앨범 */
  album?: AlbumDto;
  /** 에셋 정보 */
  asset?: AssetDto;
}
