/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Plate
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */

export interface AuthSessionInfoDto {
	/** 세션 ID */
	sessionId: string;
	/** User Agent */
	userAgent: string;
	/** IP 주소 */
	ipAddress: string;
	/** 세션 생성일 */
	createdAt: string;
	/** 마지막 활동 시간 */
	lastActivityAt: string;
	/** 현재 세션 여부 */
	isCurrent: boolean;
}
