/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Onora
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteFilter } from "./deleteFilter";

export type GetUsersParams = {
	/**
	 * @minimum 1
	 */
	skip?: number;
	/**
	 * @minimum 1
	 * @maximum 50
	 */
	take?: number;
	/**
	 * 이름 검색
	 */
	name?: string;
	/**
	 * 이메일 검색
	 */
	email?: string;
	/**
	 * 전화번호 검색
	 */
	phone?: string;
	/**
	 * 닉네임 검색
	 */
	nickname?: string;
	/**
	 * 역할 필터 (복수 선택 가능)
	 */
	roles?: string[];
	/**
	 * 상태 필터 (active: 활성, deleted: 삭제됨)
	 */
	status?: DeleteFilter;
	/**
	 * 분류 카테고리 ID
	 */
	categoryId?: string;
	/**
	 * 그룹 ID 목록 (복수 선택 가능)
	 */
	groupIds?: string[];
	/**
	 * 가입일 시작 (ISO8601)
	 */
	createdFrom?: string;
	/**
	 * 가입일 종료 (ISO8601)
	 */
	createdTo?: string;
	/**
	 * 복합 정렬 (JSON:API 컨벤션). 부호 없음=ASC, -prefix=DESC. 허용 필드: createdAt, name, email. 예: ?sort=name&sort=-createdAt
	 */
	sort?: string[];
};
