/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Plate
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */

export interface IdpAccountDto {
	/** 사용자 ID */
	id: string;
	/** 이름 */
	name: string;
	/** 이메일 */
	email: string;
	/** 활성 상태 */
	isActive: boolean;
	/** 로그인 실패 횟수 */
	failedLoginAttempts: number;
	/** 영구 잠금 여부 */
	isPermanentlyLocked: boolean;
	/**
	 * 일시 잠금 해제 시간
	 * @nullable
	 */
	lockedUntil?: string | null;
	/** 비밀번호 변경 필요 여부 */
	mustChangePassword: boolean;
	/**
	 * 마지막 로그인 시간
	 * @nullable
	 */
	lastLoginAt?: string | null;
	/**
	 * 마지막 로그인 IP
	 * @nullable
	 */
	lastLoginIp?: string | null;
	/** 가입일 */
	createdAt: string;
}
