/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Onora
 * API 문서입니다. 대부분의 엔드포인트는 쿠키 기반 JWT 인증이 필요합니다. (@Public 데코레이터가 있는 엔드포인트는 예외)
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from "./userDto";

export interface LoginResponseDto {
	/** JWT Access Token */
	accessToken: string;
	/** JWT Refresh Token */
	refreshToken: string;
	/** Access Token 만료 시간 (Unix timestamp, milliseconds) */
	accessTokenExpiresAt: number;
	/** Refresh Token 만료 시간 (Unix timestamp, milliseconds) */
	refreshTokenExpiresAt: number;
	/** 인증된 사용자 정보 */
	user: UserDto;
}
