/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Plate
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */

export interface VerifyTokenResponseDto {
	/** 토큰 유효 여부 */
	valid: boolean;
	/** Access Token 만료 시간 (Unix timestamp, ms) */
	accessTokenExpiresAt: number;
	/** Refresh Token 만료 시간 (Unix timestamp, ms) */
	refreshTokenExpiresAt: number;
	/** 현재 사용자가 tenant 역할 기준으로 FULL_ACCESS 권한을 하나라도 보유하는지 여부 */
	hasFullAccess: boolean;
}
