/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateTemplate201AllOf,
  CreateTemplateDto,
  GetTemplate200AllOf,
  GetTemplates200AllOf,
  GetTemplatesParams,
  PreviewTemplateDto,
  SendTestTemplateDto,
  ToggleTemplateStatus200AllOf,
  UpdateTemplate200AllOf,
  UpdateTemplateDto
} from '.././model';

import { customInstance } from '../../libs/customAxios';
import type { ErrorType , BodyType } from '../../libs/customAxios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 템플릿 목록을 조회합니다. 검색, 필터링, 페이지네이션을 지원합니다. System Space 전용 API입니다.
 * @summary 템플릿 목록 조회
 */
export const getTemplates = (
    params?: GetTemplatesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetTemplates200AllOf>(
      {url: `/api/v1/templates`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetTemplatesQueryKey = (params?: GetTemplatesParams,) => {
    return [
    `/api/v1/templates`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetTemplatesQueryOptions = <TData = Awaited<ReturnType<typeof getTemplates>>, TError = ErrorType<void>>(params?: GetTemplatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTemplatesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTemplates>>> = ({ signal }) => getTemplates(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTemplates>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTemplatesQueryResult = NonNullable<Awaited<ReturnType<typeof getTemplates>>>
export type GetTemplatesQueryError = ErrorType<void>


export function useGetTemplates<TData = Awaited<ReturnType<typeof getTemplates>>, TError = ErrorType<void>>(
 params: undefined |  GetTemplatesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplates>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemplates>>,
          TError,
          Awaited<ReturnType<typeof getTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemplates<TData = Awaited<ReturnType<typeof getTemplates>>, TError = ErrorType<void>>(
 params?: GetTemplatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplates>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemplates>>,
          TError,
          Awaited<ReturnType<typeof getTemplates>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemplates<TData = Awaited<ReturnType<typeof getTemplates>>, TError = ErrorType<void>>(
 params?: GetTemplatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 템플릿 목록 조회
 */

export function useGetTemplates<TData = Awaited<ReturnType<typeof getTemplates>>, TError = ErrorType<void>>(
 params?: GetTemplatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTemplatesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary 템플릿 목록 조회
 */
export const prefetchGetTemplatesQuery = async <TData = Awaited<ReturnType<typeof getTemplates>>, TError = ErrorType<void>>(
 queryClient: QueryClient, params?: GetTemplatesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplates>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetTemplatesQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * 새로운 템플릿을 등록합니다. System Space 전용 API입니다.
 * @summary 템플릿 등록
 */
export const createTemplate = (
    createTemplateDto: BodyType<CreateTemplateDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CreateTemplate201AllOf>(
      {url: `/api/v1/templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createTemplateDto, signal
    },
      options);
    }
  


export const getCreateTemplateMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTemplate>>, TError,{data: BodyType<CreateTemplateDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createTemplate>>, TError,{data: BodyType<CreateTemplateDto>}, TContext> => {

const mutationKey = ['createTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTemplate>>, {data: BodyType<CreateTemplateDto>}> = (props) => {
          const {data} = props ?? {};

          return  createTemplate(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof createTemplate>>>
    export type CreateTemplateMutationBody = BodyType<CreateTemplateDto>
    export type CreateTemplateMutationError = ErrorType<void>

    /**
 * @summary 템플릿 등록
 */
export const useCreateTemplate = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTemplate>>, TError,{data: BodyType<CreateTemplateDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTemplate>>,
        TError,
        {data: BodyType<CreateTemplateDto>},
        TContext
      > => {

      const mutationOptions = getCreateTemplateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 특정 템플릿의 상세 정보를 조회합니다. System Space 전용 API입니다.
 * @summary 템플릿 상세 조회
 */
export const getTemplate = (
    templateId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<GetTemplate200AllOf>(
      {url: `/api/v1/templates/${templateId}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTemplateQueryKey = (templateId?: string,) => {
    return [
    `/api/v1/templates/${templateId}`
    ] as const;
    }

    
export const getGetTemplateQueryOptions = <TData = Awaited<ReturnType<typeof getTemplate>>, TError = ErrorType<void>>(templateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTemplateQueryKey(templateId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTemplate>>> = ({ signal }) => getTemplate(templateId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(templateId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTemplate>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTemplateQueryResult = NonNullable<Awaited<ReturnType<typeof getTemplate>>>
export type GetTemplateQueryError = ErrorType<void>


export function useGetTemplate<TData = Awaited<ReturnType<typeof getTemplate>>, TError = ErrorType<void>>(
 templateId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemplate>>,
          TError,
          Awaited<ReturnType<typeof getTemplate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemplate<TData = Awaited<ReturnType<typeof getTemplate>>, TError = ErrorType<void>>(
 templateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTemplate>>,
          TError,
          Awaited<ReturnType<typeof getTemplate>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTemplate<TData = Awaited<ReturnType<typeof getTemplate>>, TError = ErrorType<void>>(
 templateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 템플릿 상세 조회
 */

export function useGetTemplate<TData = Awaited<ReturnType<typeof getTemplate>>, TError = ErrorType<void>>(
 templateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTemplateQueryOptions(templateId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}

/**
 * @summary 템플릿 상세 조회
 */
export const prefetchGetTemplateQuery = async <TData = Awaited<ReturnType<typeof getTemplate>>, TError = ErrorType<void>>(
 queryClient: QueryClient, templateId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTemplate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ): Promise<QueryClient> => {

  const queryOptions = getGetTemplateQueryOptions(templateId,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}



/**
 * 템플릿 정보를 수정합니다. 변경하려는 필드만 전송하면 됩니다. System Space 전용 API입니다.
 * @summary 템플릿 수정
 */
export const updateTemplate = (
    templateId: string,
    updateTemplateDto: BodyType<UpdateTemplateDto>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<UpdateTemplate200AllOf>(
      {url: `/api/v1/templates/${templateId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateTemplateDto
    },
      options);
    }
  


export const getUpdateTemplateMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTemplate>>, TError,{templateId: string;data: BodyType<UpdateTemplateDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTemplate>>, TError,{templateId: string;data: BodyType<UpdateTemplateDto>}, TContext> => {

const mutationKey = ['updateTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTemplate>>, {templateId: string;data: BodyType<UpdateTemplateDto>}> = (props) => {
          const {templateId,data} = props ?? {};

          return  updateTemplate(templateId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof updateTemplate>>>
    export type UpdateTemplateMutationBody = BodyType<UpdateTemplateDto>
    export type UpdateTemplateMutationError = ErrorType<void>

    /**
 * @summary 템플릿 수정
 */
export const useUpdateTemplate = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTemplate>>, TError,{templateId: string;data: BodyType<UpdateTemplateDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTemplate>>,
        TError,
        {templateId: string;data: BodyType<UpdateTemplateDto>},
        TContext
      > => {

      const mutationOptions = getUpdateTemplateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 템플릿을 삭제합니다. System Space 전용 API입니다.
 * @summary 템플릿 삭제
 */
export const deleteTemplate = (
    templateId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/templates/${templateId}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteTemplateMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTemplate>>, TError,{templateId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTemplate>>, TError,{templateId: string}, TContext> => {

const mutationKey = ['deleteTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTemplate>>, {templateId: string}> = (props) => {
          const {templateId} = props ?? {};

          return  deleteTemplate(templateId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTemplate>>>
    
    export type DeleteTemplateMutationError = ErrorType<void>

    /**
 * @summary 템플릿 삭제
 */
export const useDeleteTemplate = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTemplate>>, TError,{templateId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteTemplate>>,
        TError,
        {templateId: string},
        TContext
      > => {

      const mutationOptions = getDeleteTemplateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 템플릿의 활성/비활성 상태를 전환합니다. System Space 전용 API입니다.
 * @summary 템플릿 활성/비활성 토글
 */
export const toggleTemplateStatus = (
    templateId: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<ToggleTemplateStatus200AllOf>(
      {url: `/api/v1/templates/${templateId}/toggle-status`, method: 'PATCH'
    },
      options);
    }
  


export const getToggleTemplateStatusMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleTemplateStatus>>, TError,{templateId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof toggleTemplateStatus>>, TError,{templateId: string}, TContext> => {

const mutationKey = ['toggleTemplateStatus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleTemplateStatus>>, {templateId: string}> = (props) => {
          const {templateId} = props ?? {};

          return  toggleTemplateStatus(templateId,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ToggleTemplateStatusMutationResult = NonNullable<Awaited<ReturnType<typeof toggleTemplateStatus>>>
    
    export type ToggleTemplateStatusMutationError = ErrorType<void>

    /**
 * @summary 템플릿 활성/비활성 토글
 */
export const useToggleTemplateStatus = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleTemplateStatus>>, TError,{templateId: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toggleTemplateStatus>>,
        TError,
        {templateId: string},
        TContext
      > => {

      const mutationOptions = getToggleTemplateStatusMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 템플릿에 변수를 대입하여 미리보기 결과를 반환합니다. System Space 전용 API입니다.
 * @summary 템플릿 미리보기
 */
export const previewTemplate = (
    templateId: string,
    previewTemplateDto: BodyType<PreviewTemplateDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/templates/${templateId}/preview`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: previewTemplateDto, signal
    },
      options);
    }
  


export const getPreviewTemplateMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof previewTemplate>>, TError,{templateId: string;data: BodyType<PreviewTemplateDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof previewTemplate>>, TError,{templateId: string;data: BodyType<PreviewTemplateDto>}, TContext> => {

const mutationKey = ['previewTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof previewTemplate>>, {templateId: string;data: BodyType<PreviewTemplateDto>}> = (props) => {
          const {templateId,data} = props ?? {};

          return  previewTemplate(templateId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PreviewTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof previewTemplate>>>
    export type PreviewTemplateMutationBody = BodyType<PreviewTemplateDto>
    export type PreviewTemplateMutationError = ErrorType<void>

    /**
 * @summary 템플릿 미리보기
 */
export const usePreviewTemplate = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof previewTemplate>>, TError,{templateId: string;data: BodyType<PreviewTemplateDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof previewTemplate>>,
        TError,
        {templateId: string;data: BodyType<PreviewTemplateDto>},
        TContext
      > => {

      const mutationOptions = getPreviewTemplateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * 템플릿을 테스트 수신자에게 발송합니다. System Space 전용 API입니다.
 * @summary 템플릿 발송 테스트
 */
export const sendTestTemplate = (
    templateId: string,
    sendTestTemplateDto: BodyType<SendTestTemplateDto>,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/api/v1/templates/${templateId}/send-test`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendTestTemplateDto, signal
    },
      options);
    }
  


export const getSendTestTemplateMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendTestTemplate>>, TError,{templateId: string;data: BodyType<SendTestTemplateDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sendTestTemplate>>, TError,{templateId: string;data: BodyType<SendTestTemplateDto>}, TContext> => {

const mutationKey = ['sendTestTemplate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendTestTemplate>>, {templateId: string;data: BodyType<SendTestTemplateDto>}> = (props) => {
          const {templateId,data} = props ?? {};

          return  sendTestTemplate(templateId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SendTestTemplateMutationResult = NonNullable<Awaited<ReturnType<typeof sendTestTemplate>>>
    export type SendTestTemplateMutationBody = BodyType<SendTestTemplateDto>
    export type SendTestTemplateMutationError = ErrorType<void>

    /**
 * @summary 템플릿 발송 테스트
 */
export const useSendTestTemplate = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendTestTemplate>>, TError,{templateId: string;data: BodyType<SendTestTemplateDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendTestTemplate>>,
        TError,
        {templateId: string;data: BodyType<SendTestTemplateDto>},
        TContext
      > => {

      const mutationOptions = getSendTestTemplateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    