export enum ReservationAvailabilityStatus {
	AVAILABLE = "AVAILABLE",
	FEW_LEFT = "FEW_LEFT",
	WAITLIST_OPEN = "WAITLIST_OPEN",
	RESERVED = "RESERVED",
	WAITLISTED = "WAITLISTED",
	BOOKING_CLOSED = "BOOKING_CLOSED",
}
