/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Plate
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  BatchAssignGrantsToRole200AllOf,
  BatchAssignRoleGrantRequestDto
} from '.././model';

import { customInstance } from '../../libs/customAxios';
import type { ErrorType , BodyType } from '../../libs/customAxios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 특정 Role에 Ability를 배치로 할당/해제합니다. 전체 목록 동기화 방식입니다.
 * @summary 역할별 권한 배치 할당
 */
export const batchAssignGrantsToRole = (
    roleId: string,
    batchAssignRoleGrantRequestDto: BodyType<BatchAssignRoleGrantRequestDto>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<BatchAssignGrantsToRole200AllOf>(
      {url: `/api/v1/grants/roles/${roleId}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: batchAssignRoleGrantRequestDto
    },
      options);
    }
  


export const getBatchAssignGrantsToRoleMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof batchAssignGrantsToRole>>, TError,{roleId: string;data: BodyType<BatchAssignRoleGrantRequestDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof batchAssignGrantsToRole>>, TError,{roleId: string;data: BodyType<BatchAssignRoleGrantRequestDto>}, TContext> => {

const mutationKey = ['batchAssignGrantsToRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof batchAssignGrantsToRole>>, {roleId: string;data: BodyType<BatchAssignRoleGrantRequestDto>}> = (props) => {
          const {roleId,data} = props ?? {};

          return  batchAssignGrantsToRole(roleId,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type BatchAssignGrantsToRoleMutationResult = NonNullable<Awaited<ReturnType<typeof batchAssignGrantsToRole>>>
    export type BatchAssignGrantsToRoleMutationBody = BodyType<BatchAssignRoleGrantRequestDto>
    export type BatchAssignGrantsToRoleMutationError = ErrorType<void>

    /**
 * @summary 역할별 권한 배치 할당
 */
export const useBatchAssignGrantsToRole = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof batchAssignGrantsToRole>>, TError,{roleId: string;data: BodyType<BatchAssignRoleGrantRequestDto>}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof batchAssignGrantsToRole>>,
        TError,
        {roleId: string;data: BodyType<BatchAssignRoleGrantRequestDto>},
        TContext
      > => {

      const mutationOptions = getBatchAssignGrantsToRoleMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    