/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { AugmentedZodDtoName } from './augmentedZodDtoName';
import type { AugmentedZodDtoNameOptionsItem } from './augmentedZodDtoNameOptionsItem';

export interface AugmentedZodDto {
  name: AugmentedZodDtoName;
  nameOptions: AugmentedZodDtoNameOptionsItem[];
}
