/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type CategoryDtoParentId = { [key: string]: any } | null;
