/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { CategoryDtoParentId } from './categoryDtoParentId';

export interface CategoryDto {
  ancestorIds: string[];
  createdAt: string;
  deletedAt?: string;
  id: string;
  name: string;
  parentId: CategoryDtoParentId;
  serviceId: string;
  spaceId: string;
  updatedAt?: string;
}
