/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCategoryDtoParentId } from './createCategoryDtoParentId';

export interface CreateCategoryDto {
  ancestorIds: string[];
  name: string;
  /** @nullable */
  parentId: CreateCategoryDtoParentId;
  serviceId: string;
  spaceId: string;
}
