/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCategoryDtoParentId } from './createCategoryDtoParentId';

export interface CreateCategoryDto {
  ancestorIds: string[];
  name: string;
  parentId: CreateCategoryDtoParentId;
  serviceId: string;
  spaceId: string;
}
