/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateContentDto } from './createContentDto';

export interface CreateExerciseDto {
  duration: number;
  count: number;
  taskName: string;
  taskLabel: string;
  content: CreateContentDto;
  tenancyId: string;
}
