/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { TenantDto } from './tenantDto';

export type DeleteTenant200AllOf = {
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  data?: TenantDto;
};
