/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { Object } from './object';
import type { GetAdminMainGroupsRoute200AllOfMeta } from './getAdminMainGroupsRoute200AllOfMeta';

export type GetAdminMainGroupsRoute200AllOf = {
  data?: Object[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetAdminMainGroupsRoute200AllOfMeta;
};
