/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */
import type { Object } from './object';
import type { GetAdminMainServicesRoute200AllOfMeta } from './getAdminMainServicesRoute200AllOfMeta';

export type GetAdminMainServicesRoute200AllOf = {
  data?: Object[];
  /** */
  httpStatus?: number;
  /** */
  message?: string;
  meta?: GetAdminMainServicesRoute200AllOfMeta;
};
