/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateNames } from './templateNames';
import type { SortOrder } from './sortOrder';

export type GetTemplatesByQueryParams = {
name?: TemplateNames;
htmlContent?: string;
id?: string;
createdAtSortOrder?: SortOrder;
skip?: number;
take?: number;
};
