/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { Roles } from './roles';

export interface RoleDto {
  createdAt: string;
  id: string;
  name: Roles;
  /** @nullable */
  removedAt: string | null;
  updatedAt: string;
}
