/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceDtoCreatedAt } from './serviceDtoCreatedAt';
import type { ServiceDtoDeletedAt } from './serviceDtoDeletedAt';
import type { ServiceDtoName } from './serviceDtoName';
import type { ServiceDtoUpdatedAt } from './serviceDtoUpdatedAt';

export interface ServiceDto {
  createdAt: ServiceDtoCreatedAt;
  deletedAt?: ServiceDtoDeletedAt;
  id: string;
  name: ServiceDtoName;
  updatedAt?: ServiceDtoUpdatedAt;
}
