/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceFormDtoName } from './serviceFormDtoName';
import type { ServiceFormDtoNameOptionsItem } from './serviceFormDtoNameOptionsItem';

export interface ServiceFormDto {
  name: ServiceFormDtoName;
  nameOptions: ServiceFormDtoNameOptionsItem[];
}
