/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceEntityName } from './serviceEntityName';
import type { ServiceEntityRemovedAt } from './serviceEntityRemovedAt';
import type { ServiceEntityUpdatedAt } from './serviceEntityUpdatedAt';

export interface ServiceEntity {
  createdAt: string;
  id: string;
  /** @nullable */
  label: string | null;
  name: ServiceEntityName;
  removedAt: ServiceEntityRemovedAt;
  updatedAt: ServiceEntityUpdatedAt;
}
