/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateNames } from './templateNames';

export interface TemplateDto {
  createdAt: string;
  htmlContent: string;
  id: string;
  name: TemplateNames;
  /** @nullable */
  removedAt: string | null;
  updatedAt: string;
}
