/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

export type TenantTypes = typeof TenantTypes[keyof typeof TenantTypes];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TenantTypes = {
  PHYSICAL: 'PHYSICAL',
  ABSTRACT: 'ABSTRACT',
} as const;
