/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateServiceDtoName } from './updateServiceDtoName';
import type { UpdateServiceDtoRemovedAt } from './updateServiceDtoRemovedAt';
import type { UpdateServiceDtoUpdatedAt } from './updateServiceDtoUpdatedAt';

export interface UpdateServiceDto {
  createdAt?: string;
  id?: string;
  /** @nullable */
  label?: string | null;
  name?: UpdateServiceDtoName;
  removedAt?: UpdateServiceDtoRemovedAt;
  updatedAt?: UpdateServiceDtoUpdatedAt;
}
