/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateCategoryDto {
  createdAt?: string;
  id?: string;
  /** @nullable */
  removedAt?: string | null;
  /** @nullable */
  updatedAt?: string | null;
}
