/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { TemplateNames } from './templateNames';
import type { UpdatePostDto } from './updatePostDto';

export interface UpdateTemplateDto {
  id: string;
  keys?: string[];
  name?: TemplateNames;
  postId?: string;
  serviceId?: string;
  updatePostDto: UpdatePostDto;
}
