/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateProgramDto {
  routineId?: string;
  sessionId?: string;
  tenancyId?: string;
}
