/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * PROMISE Server
 * OpenAPI spec version: 1.0.0
 */
import type { ProfileDto } from './profileDto';

export interface UserDto {
  createdAt: string;
  email: string;
  id: string;
  name: string;
  /** @minLength 6 */
  password: string;
  phone: string;
  /** @nullable */
  profiles: ProfileDto[] | null;
  /** @nullable */
  removedAt: string | null;
  updatedAt: string;
}
