export const COLUMN_FIELDS = {
  name: "name",
  actionKey: "actionKey",
  subjectKey: "subjectKey",
  roleKey: "roleKey",
  displayName: "displayName",
  group: "group",
  label: "label",
  email: "email",
  phone: "phone",
  description: "description",
  createdAt: "createdAt",
  signedUpAt: "signedUpAt",
  receivedAt: "receivedAt",
  occurredAt: "occurredAt",
  removedAt: "removedAt",
  status: "status",
  isActive: "isActive",
  id: "id",
  actions: "actions",
  role: "role",
  order: "order",
  isSystem: "isSystem",
  duration: "duration",
  count: "count",
  code: "code",
  businessNo: "businessNo",
  address: "address",
  originalName: "originalName",
  kind: "kind",
  mimeType: "mimeType",
  sizeBytes: "sizeBytes",
  customerName: "customerName",
  title: "title",
  category: "category",
  channel: "channel",
  priority: "priority",
  assigneeName: "assigneeName",
  sentiment: "sentiment",
  slaStatus: "slaStatus",
  unreadCount: "unreadCount",
  clientId: "clientId",
  clientName: "clientName",
  tokenEndpointAuthMethod: "tokenEndpointAuthMethod",
  grantTypes: "grantTypes",
  isPermanentlyLocked: "isPermanentlyLocked",
  failedLoginAttempts: "failedLoginAttempts",
  lastLoginAt: "lastLoginAt",
  result: "result",
  failureReason: "failureReason",
  ipAddress: "ipAddress",
  userAgent: "userAgent",
  key: "key",
  modelType: "modelType",
  accountId: "accountId",
  grantId: "grantId",
  expiresAt: "expiresAt",
  subjectLabel: "subjectLabel",
  actionLabel: "actionLabel",
  inverted: "inverted",
  fieldCount: "fieldCount",
  hasConditions: "hasConditions",
} as const;

export const COLUMN_LABELS = {
  name: "이름",
  actionKey: "행위 식별자",
  subjectKey: "Subject 식별자",
  roleKey: "역할 식별자",
  displayName: "표시명",
  group: "분류",
  label: "라벨",
  email: "이메일",
  phone: "전화번호",
  description: "설명",
  createdAt: "등록일",
  signedUpAt: "가입일",
  receivedAt: "접수일",
  occurredAt: "시간",
  status: "상태",
  isActive: "활성",
  actions: "",
  role: "역할",
  order: "순서",
  isSystem: "시스템",
  duration: "지속시간",
  count: "반복횟수",
  code: "템플릿 코드",
  businessNo: "사업자등록번호",
  address: "주소",
  originalName: "파일명",
  kind: "타입",
  mimeType: "MIME",
  sizeBytes: "크기",
  customerName: "고객",
  title: "제목",
  category: "카테고리",
  channel: "채널",
  priority: "우선순위",
  assigneeName: "담당자",
  sentiment: "감성",
  slaStatus: "SLA",
  unreadCount: "미확인",
  clientId: "Client ID",
  clientName: "이름",
  tokenEndpointAuthMethod: "인증 방식",
  grantTypes: "Grant Types",
  isPermanentlyLocked: "잠금 상태",
  failedLoginAttempts: "실패 횟수",
  lastLoginAt: "최종 로그인",
  result: "결과",
  failureReason: "실패 사유",
  ipAddress: "IP 주소",
  userAgent: "User Agent",
  key: "키",
  modelType: "모델 타입",
  accountId: "Account ID",
  grantId: "Grant ID",
  expiresAt: "만료 시간",
  subjectLabel: "Subject",
  actionLabel: "Action",
  inverted: "유형",
  fieldCount: "필드 수",
  hasConditions: "조건",
} as const;
