/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import type { ActionResponseDto } from "./actionResponseDto";
import type { SubjectResponseDto } from "./subjectResponseDto";
import type { AbilityResponseDtoConditions } from "./abilityResponseDtoConditions";

export interface AbilityResponseDto {
	/** Ability ID (UUID) */
	id: string;
	/** Action ID (UUID) */
	actionId: string;
	/** Action 상세 정보 */
	action?: ActionResponseDto;
	/** Subject ID (UUID) */
	subjectId: string;
	/** Subject 상세 정보 */
	subject?: SubjectResponseDto;
	/** 대상 필드 목록 */
	fields: string[];
	/**
	 * 권한 조건 (JSON 형식)
	 * @nullable
	 */
	conditions?: AbilityResponseDtoConditions;
	/** 거부 권한 여부 (true: cannot, false: can) */
	inverted: boolean;
	/**
	 * 거부 사유
	 * @nullable
	 */
	reason?: string | null;
	/** 권한 이름 (고유 식별자) */
	name: string;
	/**
	 * 권한 설명
	 * @nullable
	 */
	description?: string | null;
	/** 생성 일시 */
	createdAt: string;
	/**
	 * 수정 일시
	 * @nullable
	 */
	updatedAt?: string | null;
}
