/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * core-api
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import type { ActionResponseDtoConfig } from "./actionResponseDtoConfig";

export interface ActionResponseDto {
	/** Action ID (UUID) */
	id: string;
	/** Action 이름 (create, read, read:masked:email 등) */
	name: string;
	/**
	 * 표시명
	 * @nullable
	 */
	displayName?: string | null;
	/**
	 * 설명
	 * @nullable
	 */
	description?: string | null;
	/**
	 * 그룹 (crud, visibility, bulk, workflow)
	 * @nullable
	 */
	group?: string | null;
	/** 정렬 순서 */
	order: number;
	/** 시스템 여부 (시스템 기본 Action인지) */
	isSystem: boolean;
	/**
	 * Action 설정 (마스킹, 포맷팅 등)
	 * @nullable
	 */
	config?: ActionResponseDtoConfig;
	/** 생성 일시 */
	createdAt: string;
	/**
	 * 수정 일시
	 * @nullable
	 */
	updatedAt?: string | null;
}
