/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 */
import type { ReservationCheckoutResultDto } from "./reservationCheckoutResultDto";

export type CreateReservationCheckout201AllOf = {
	httpStatus?: number;
	message?: string;
	data?: ReservationCheckoutResultDto;
};
