/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import type { PaymentStatus } from './paymentStatus';
import type { CreatePaymentDtoMethod } from './createPaymentDtoMethod';
import type { CreatePaymentDtoMetadata } from './createPaymentDtoMetadata';
import type { CreatePaymentSubjectDto } from './createPaymentSubjectDto';
import type { CreatePaymentReferenceDto } from './createPaymentReferenceDto';

export interface CreatePaymentDto {
  /**
   * 결제자 User ID
   * @nullable
   */
  payerUserId?: string | null;
  /**
   * 결제명
   * @minLength 1
   * @maxLength 160
   */
  title: string;
  /** 결제 상태 */
  status?: PaymentStatus;
  /**
   * 결제 수단
   * @nullable
   */
  method?: CreatePaymentDtoMethod;
  /**
   * 결제 제공자
   * @maxLength 80
   * @nullable
   */
  provider?: string | null;
  /**
   * 결제 제공자 결제 ID
   * @maxLength 160
   * @nullable
   */
  providerPaymentId?: string | null;
  /**
   * 결제 제공자 주문 ID
   * @maxLength 160
   * @nullable
   */
  providerOrderId?: string | null;
  /**
   * 총 결제 금액. 생략하면 subjects 합계로 계산합니다.
   * @minimum 0
   */
  totalAmount?: number;
  /**
   * 통화 코드
   * @minLength 3
   * @maxLength 3
   */
  currency?: string;
  /**
   * 결제 요청 시각
   * @nullable
   */
  requestedAt?: string | null;
  /**
   * 결제 승인 시각
   * @nullable
   */
  approvedAt?: string | null;
  /**
   * 결제 취소 시각
   * @nullable
   */
  canceledAt?: string | null;
  /**
   * 영수증 URL
   * @maxLength 1000
   * @nullable
   */
  receiptUrl?: string | null;
  /**
   * 관리 메모
   * @maxLength 1000
   * @nullable
   */
  memo?: string | null;
  /**
   * 결제 metadata
   * @nullable
   */
  metadata?: CreatePaymentDtoMetadata;
  /** 결제 대상 목록 */
  subjects?: CreatePaymentSubjectDto[];
  /** 결제 참조 목록 */
  references?: CreatePaymentReferenceDto[];
}
