/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * core-api
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import type { FillInquiryFormRequestDtoMode } from "./fillInquiryFormRequestDtoMode";
import type { FillInquiryFormRequestDtoCurrentObject } from "./fillInquiryFormRequestDtoCurrentObject";

export interface FillInquiryFormRequestDto {
	/** 폼 모드 */
	mode: FillInquiryFormRequestDtoMode;
	/** 선택한 AI 스키마 키 */
	schemaKey: string;
	/** 선택한 경로 목록 */
	selectedPaths: string[];
	/** 현재 폼 객체 */
	currentObject: FillInquiryFormRequestDtoCurrentObject;
	/** 추가 프롬프트 */
	userPrompt?: string;
}
