/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import type { AssetKind } from "./assetKind";
import type { AssetStatus } from "./assetStatus";
import type { DeleteFilter } from "./deleteFilter";

export type GetAssetsParams = {
	/**
	 * @minimum 0
	 */
	skip?: number;
	/**
	 * @minimum 1
	 * @maximum 200
	 */
	take?: number;
	/**
	 * 폴더 ID 필터
	 */
	folderId?: string;
	/**
	 * 스페이스 ID 필터
	 */
	spaceId?: string;
	/**
	 * 에셋 타입 필터
	 */
	kind?: AssetKind;
	/**
	 * 업로드 상태 필터
	 */
	status?: AssetStatus;
	/**
	 * 파일명 검색 (부분 일치)
	 */
	search?: string;
	/**
	 * 상태 필터 (active: 활성, deleted: 삭제됨)
	 */
	statusFilter?: DeleteFilter;
	/**
	 * 복합 정렬 (JSON:API 컨벤션). 부호 없음=ASC, -prefix=DESC. 허용 필드: createdAt, originalName, sizeBytes. 예: ?sort=originalName&sort=-createdAt
	 */
	sort?: string[];
};
