/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 */

export type GetCommunityPostsParams = {
	/**
	 * 조회 시작 위치
	 * @minimum 0
	 */
	skip?: number;
	/**
	 * 조회 개수
	 * @minimum 1
	 */
	take?: number;
};
