/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Plate
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteFilter } from "./deleteFilter";

export type GetFoldersParams = {
	/**
	 * @minimum 0
	 */
	skip?: number;
	/**
	 * @minimum 1
	 * @maximum 50
	 */
	take?: number;
	/**
	 * 상위 폴더 ID 필터 (null이면 루트)
	 */
	parentFolderId?: string;
	/**
	 * 스페이스 ID 필터
	 */
	spaceId?: string;
	/**
	 * 폴더명 검색 (부분 일치)
	 */
	name?: string;
	/**
	 * 상태 필터 (active: 활성, deleted: 삭제됨)
	 */
	statusFilter?: DeleteFilter;
	/**
	 * 복합 정렬 (JSON:API 컨벤션). 부호 없음=ASC, -prefix=DESC. 허용 필드: createdAt, name, sortOrder. 예: ?sort=sortOrder&sort=name
	 */
	sort?: string[];
};
