/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */

export type GetRoutines200AllOfMeta = {
  /** 전체 항목 수 */
  total?: number;
  /** 현재 페이지 */
  page?: number;
  /** 페이지당 항목 수 */
  limit?: number;
  /** 전체 페이지 수 */
  totalPages?: number;
};
