/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import type { InquiryParticipantRole } from "./inquiryParticipantRole";

export interface InquiryParticipantDto {
	id: string;
	createdAt: string;
	updatedAt: string;
	/** @nullable */
	removedAt: string | null;
	/** 소속 문의 ID */
	inquiryId: string;
	/** 소속 스레드 ID */
	threadId?: string;
	/** 참여자 ID */
	userId: string;
	/** 참여자 이름 */
	userName: string;
	/**
	 * 참여자 아바타
	 * @nullable
	 */
	userAvatar: string | null;
	/** 참여자 역할 */
	role: InquiryParticipantRole;
	/** 온라인 여부 */
	isOnline: boolean;
	/** 타이핑 중 여부 */
	isTyping: boolean;
	/**
	 * 마지막 접속 시간
	 * @nullable
	 */
	lastSeenAt: string | null;
	/**
	 * 마지막 읽은 시간
	 * @nullable
	 */
	lastReadAt: string | null;
	/** 읽지 않은 메시지 수 */
	unreadCount: number;
	/** 참여 일시 */
	joinedAt: string;
	/**
	 * 나간 일시
	 * @nullable
	 */
	leftAt: string | null;
}
