/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */

export interface ReservationCheckoutContextDto {
	/** 피드 항목 ID */
	feedItemId: string;
	/** 타임라인 ID */
	timelineId: string;
	/** 세션 ID */
	sessionId: string;
	/** 프로그램 ID */
	programId: string;
	/** 예약 회차 시작 시각 */
	occurrenceStartAt: string;
	/** 예약 회차 종료 시각 */
	occurrenceEndsAt: string;
	/** 타임라인 이름 */
	timelineName: string;
	/** 세션 이름 */
	sessionName: string;
	/** 프로그램 이름 */
	programName: string;
	/**
	 * 코치 이름
	 * @nullable
	 */
	coachName?: string | null;
}
