/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 */
import type { PaymentMethod } from "./paymentMethod";
import type { ReservationCheckoutContextDto } from "./reservationCheckoutContextDto";
import type { ReservationCheckoutOptionDto } from "./reservationCheckoutOptionDto";

export interface ReservationCheckoutBootstrapDto {
	context: ReservationCheckoutContextDto;
	options: ReservationCheckoutOptionDto[];
	paymentMethods: PaymentMethod[];
}
