/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. Core API와 IDP 관리 API를 함께 제공합니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송

**Tenant Scope:**
- 보호 API는 `x-tenant-id` header로 현재 Tenant를 선택합니다.
- 서버는 Tenant에서 Space를 파생하고, 기본적으로 현재 Space와 모든 하위 Space category 리소스를 조회합니다.
- `@WithAncestorSpaces`/`@WithSpaceTree`가 적용된 API는 Swagger JSON의 `x-space-resource-scope` 확장 필드로 scope를 표시합니다.
 * OpenAPI spec version: 1.0.0
 */

import type { ProgramDto } from "./programDto";
import type { ReservationStatus } from "./reservationStatus";
import type { SessionDto } from "./sessionDto";
import type { TimelineDto } from "./timelineDto";
import type { UserDto } from "./userDto";

export interface ReservationDto {
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|[A-Za-z0-9_-]{22})$ */
	id: string;
	createdAt: string;
	updatedAt: string;
	/** @nullable */
	removedAt: string | null;
	/**
	 * Space ID
	 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|[A-Za-z0-9_-]{22})$
	 */
	spaceId: string;
	/**
	 * 생성자 ID
	 * @nullable
	 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|[A-Za-z0-9_-]{22})$
	 */
	createdById?: string | null;
	/**
	 * 예약 사용자 ID
	 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|[A-Za-z0-9_-]{22})$
	 */
	userId: string;
	/**
	 * 타임라인 ID
	 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|[A-Za-z0-9_-]{22})$
	 */
	timelineId: string;
	/**
	 * 세션 ID
	 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|[A-Za-z0-9_-]{22})$
	 */
	sessionId: string;
	/**
	 * 프로그램 ID
	 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|[A-Za-z0-9_-]{22})$
	 */
	programId: string;
	/** 예약 발생 회차 시작 시각 */
	occurrenceStartAt: string;
	/** 예약 상태 */
	status: ReservationStatus;
	/**
	 * 예약 메모
	 * @nullable
	 */
	memo?: string | null;
	/** 멱등성 키 */
	idempotencyKey: string;
	/**
	 * 대기 순번
	 * @minimum 1
	 * @nullable
	 */
	waitlistPosition?: number | null;
	/**
	 * 확정 시각
	 * @nullable
	 */
	confirmedAt: string | null;
	/**
	 * 취소 시각
	 * @nullable
	 */
	canceledAt: string | null;
	/**
	 * 취소 사유
	 * @nullable
	 */
	cancelReason?: string | null;
	user?: UserDto;
	timeline?: TimelineDto;
	session?: SessionDto;
	program?: ProgramDto;
}
