/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. Core API와 IDP 관리 API를 함께 제공합니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */

export interface SignUpPayloadDto {
  /** 닉네임 (2-50자) */
  nickname: string;
  /** 스페이스 ID (UUID) */
  spaceId: string;
  /** 이메일 */
  email: string;
  /** 이름 (2-50자) */
  name: string;
  /** 전화번호 */
  phone: string;
  /** 주소 (2-255자) */
  address: string;
  /** 비밀번호 (8자 이상) */
  password: string;
}
