/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Plate
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import type { SyncRolePolicyItemDto } from "./syncRolePolicyItemDto";

export interface SyncRolePoliciesDto {
	/** Role에 연결할 Policy 목록입니다. 전체 동기화 방식으로 반영됩니다. */
	rolePolicies: SyncRolePolicyItemDto[];
}
