/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * core-api
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import type { TenantAccessRequestStatus } from "./tenantAccessRequestStatus";
import type { UserDto } from "./userDto";
import type { TenantAccessRequestDtoReviewer } from "./tenantAccessRequestDtoReviewer";
import type { SpaceDto } from "./spaceDto";
import type { RoleDto } from "./roleDto";
import type { TenantAccessRequestDtoPreviousRole } from "./tenantAccessRequestDtoPreviousRole";
import type { TenantAccessRequestDtoAppliedTenant } from "./tenantAccessRequestDtoAppliedTenant";

export interface TenantAccessRequestDto {
	id: string;
	createdAt: string;
	updatedAt: string;
	/** @nullable */
	removedAt: string | null;
	/** 신청자 ID */
	requesterId: string;
	/** 신청 대상 Space ID */
	spaceId: string;
	/** 희망 Role ID */
	requestedRoleId: string;
	/**
	 * 신청 시점 기존 Role ID
	 * @nullable
	 */
	previousRoleId?: string | null;
	/**
	 * 신청 사유
	 * @nullable
	 */
	reason?: string | null;
	/** 신청 상태 */
	status: TenantAccessRequestStatus;
	/**
	 * 검토자 ID
	 * @nullable
	 */
	reviewerId?: string | null;
	/**
	 * 검토 코멘트
	 * @nullable
	 */
	reviewComment?: string | null;
	/**
	 * 검토 시각
	 * @nullable
	 */
	reviewedAt: string | null;
	/**
	 * 승인 적용 Tenant ID
	 * @nullable
	 */
	appliedTenantId?: string | null;
	requester?: UserDto;
	/** @nullable */
	reviewer?: TenantAccessRequestDtoReviewer;
	space?: SpaceDto;
	requestedRole?: RoleDto;
	/** @nullable */
	previousRole?: TenantAccessRequestDtoPreviousRole;
	/** @nullable */
	appliedTenant?: TenantAccessRequestDtoAppliedTenant;
}
