/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. Core API와 IDP 관리 API를 함께 제공합니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송

**Tenant Scope:**
- 보호 API는 `x-tenant-id` header로 현재 Tenant를 선택합니다.
- 서버는 Tenant에서 Space를 파생하고, 기본적으로 현재 Space와 모든 하위 Space category 리소스를 조회합니다.
- `@WithAncestorSpaces`/`@WithSpaceTree`가 적용된 API는 Swagger JSON의 `x-space-resource-scope` 확장 필드로 scope를 표시합니다.
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateAbilityDtoConditions } from "./updateAbilityDtoConditions";

export interface UpdateAbilityDto {
	/** Action ID (UUID) */
	actionId?: string;
	/** Subject ID (UUID) */
	subjectId?: string;
	/** 대상 필드 목록 (빈 배열이면 전체 필드) */
	fields?: string[];
	/** 권한 조건 (JSON 형식) */
	conditions?: UpdateAbilityDtoConditions;
	/** 거부 권한 여부 (true: cannot, false: can) */
	inverted?: boolean;
	/** 거부 사유 (inverted=true일 때 사용) */
	reason?: string;
	/** 권한 이름 */
	name?: string;
	/** 권한 설명 */
	description?: string;
}
