/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import type { CoursePassKind } from "./coursePassKind";
import type { CoursePassStatus } from "./coursePassStatus";

export interface UpdateCoursePassDto {
	/** 수강권 종류 */
	kind?: CoursePassKind;
	/** 수강권 유효 시작일 */
	validFrom?: string;
	/** 수강권 만료일 */
	expiresAt?: string;
	/**
	 * 예약 가능 횟수
	 * @minimum 0
	 */
	reservationLimit?: number;
	/**
	 * 사용한 예약 횟수
	 * @minimum 0
	 */
	reservationUsedCount?: number;
	/**
	 * 남은 예약 횟수
	 * @minimum 0
	 */
	reservationRemainingCount?: number;
	/** 수강권 상태 */
	status?: CoursePassStatus;
}
