/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. Core API와 IDP 관리 API를 함께 제공합니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송

**Tenant Scope:**
- 보호 API는 `x-tenant-id` header로 현재 Tenant를 선택합니다.
- 서버는 Tenant에서 Space를 파생하고, 기본적으로 현재 Space와 모든 하위 Space category 리소스를 조회합니다.
- `@WithAncestorSpaces`/`@WithSpaceTree`가 적용된 API는 Swagger JSON의 `x-space-resource-scope` 확장 필드로 scope를 표시합니다.
 * OpenAPI spec version: 1.0.0
 */

export interface UserStatsDto {
	/** 전체 사용자 수 */
	total: number;
	/** 활성 사용자 수 (최근 30일 내 활동) */
	active: number;
	/** 비활성 사용자 수 (30일 이상 미활동) */
	inactive: number;
	/** 이번 달 신규 가입자 수 */
	newThisMonth: number;
}
