module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  rootDir: ".",
  testMatch: ["**/__tests__/**/*.spec.ts", "**/__tests__/**/*.test.ts"],
  moduleFileExtensions: ["ts", "js", "json"],
  setupFiles: ["reflect-metadata"],
  moduleNameMapper: {
    "^@cocrepo/repository$": "<rootDir>/../be-repository/dist",
    "^@cocrepo/context$": "<rootDir>/../be-context/dist",
    "^@cocrepo/prisma$": "<rootDir>/__tests__/mocks/prisma.ts",
    "^@cocrepo/entity$": "<rootDir>/../be-entity/dist",
    "^@cocrepo/vo$": "<rootDir>/../be-vo/dist",
    "^@cocrepo/dto$": "<rootDir>/../be-dto/dist",
    "^@cocrepo/toolkit$": "<rootDir>/../common-toolkit/dist",
    "^@cocrepo/constant$": "<rootDir>/../common-constant/dist",
    "^@cocrepo/type$": "<rootDir>/../common-type/dist",
    "^@cocrepo/decorator$": "<rootDir>/../be-decorator/dist",
  },
  transform: {
    "^.+\\.ts$": [
      "ts-jest",
      {
        tsconfig: {
          module: "commonjs",
          target: "es2022",
          esModuleInterop: true,
          allowSyntheticDefaultImports: true,
          experimentalDecorators: true,
          emitDecoratorMetadata: true,
          types: ["jest", "node"],
          skipLibCheck: true,
          strict: false,
        },
      },
    ],
  },
  collectCoverageFrom: [
    "src/**/*.ts",
    "!src/**/*.spec.ts",
    "!src/**/*.test.ts",
    "!src/**/*.d.ts",
    "!src/**/index.ts",
  ],
  coverageDirectory: "./coverage",
  coverageReporters: ["text", "lcov", "html"],
  maxWorkers: 1,
  testTimeout: 10000,
  forceExit: true,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};
