/**
 * Generated by orval 🍺
 * Do not edit manually.
 * OIDC Identity Provider
 * OpenID Connect Identity Provider API
 *
 * OIDC 인증 및 IDP 관리 API를 제공합니다.
 *
 * **인증 방법:**
 * 1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
 * 2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */

export interface AuditLogStatsDto {
  /** 오늘 성공 건수 */
  todaySuccessCount: number;
  /** 오늘 실패 건수 */
  todayFailureCount: number;
  /** 오늘 잠금 건수 */
  todayLockedCount: number;
  /** 전체 건수 */
  totalCount: number;
}
