/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. Core API와 IDP 관리 API를 함께 제공합니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */

export interface CommunityPostDto {
  /** 커뮤니티 게시글 ID */
  id: string;
  /**
   * 게시글 제목
   * @maxLength 80
   * @nullable
   */
  title?: string | null;
  /**
   * 게시글 본문
   * @maxLength 1000
   */
  text: string;
  /** 작성자 표시 이름 */
  authorName: string;
  /** 작성 시각 */
  createdAt: string;
  /** 현재 로그인 사용자가 작성한 글 여부 */
  isMine: boolean;
  /** 공지/고정 게시글 여부 */
  isPinned: boolean;
}
