/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. Core API와 IDP 관리 API를 함께 제공합니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import type { CreateTranslationDtoLanguageCode } from './createTranslationDtoLanguageCode';

export interface CreateTranslationDto {
  /** 언어 코드 */
  languageCode: CreateTranslationDtoLanguageCode;
  /** 번역 키 (예: 성공, 번역 목록 조회 성공) */
  key: string;
  /** 번역된 텍스트 */
  text: string;
  /** 카테고리 (common, error, validation, menu, role) */
  category: string;
  /** 번역 완료 여부 */
  isTranslated: boolean;
}
