/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. Core API와 IDP 관리 API를 함께 제공합니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import type { ThreadStatus } from './threadStatus';

export interface InquiryThreadDto {
  id: string;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  removedAt: string | null;
  /** 소속 문의 ID */
  inquiryId: string;
  /**
   * 스레드 제목
   * @nullable
   */
  title: string | null;
  /** 스레드 상태 */
  status: ThreadStatus;
  /** 생성자 ID */
  createdBy: string;
  /**
   * 마지막 메시지 일시
   * @nullable
   */
  lastMessageAt: string | null;
  /**
   * 마지막 메시지 미리보기
   * @nullable
   */
  lastMessagePreview: string | null;
  /** 메시지 수 */
  messageCount: number;
}
