/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. Core API와 IDP 관리 API를 함께 제공합니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송

**Tenant Scope:**
- 보호 API는 `x-tenant-id` header로 현재 Tenant를 선택합니다.
- 서버는 Tenant에서 Space를 파생하고, 기본적으로 현재 Space와 모든 하위 Space category 리소스를 조회합니다.
- `@WithAncestorSpaces`/`@WithSpaceTree`가 적용된 API는 Swagger JSON의 `x-space-resource-scope` 확장 필드로 scope를 표시합니다.
 * OpenAPI spec version: 1.0.0
 */

import type { RoleDto } from "./roleDto";
import type { SpaceDto } from "./spaceDto";
import type { TenantAccessRequestDtoAppliedTenant } from "./tenantAccessRequestDtoAppliedTenant";
import type { TenantAccessRequestDtoPreviousRole } from "./tenantAccessRequestDtoPreviousRole";
import type { TenantAccessRequestDtoReviewer } from "./tenantAccessRequestDtoReviewer";
import type { TenantAccessRequestStatus } from "./tenantAccessRequestStatus";
import type { UserDto } from "./userDto";

export interface TenantAccessRequestDto {
	/** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|[A-Za-z0-9_-]{22})$ */
	id: string;
	createdAt: string;
	updatedAt: string;
	/** @nullable */
	removedAt: string | null;
	/**
	 * 신청자 ID
	 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|[A-Za-z0-9_-]{22})$
	 */
	requesterId: string;
	/**
	 * 신청 대상 Space ID
	 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|[A-Za-z0-9_-]{22})$
	 */
	spaceId: string;
	/**
	 * 희망 Role ID
	 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|[A-Za-z0-9_-]{22})$
	 */
	requestedRoleId: string;
	/**
	 * 신청 시점 기존 Role ID
	 * @nullable
	 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|[A-Za-z0-9_-]{22})$
	 */
	previousRoleId?: string | null;
	/**
	 * 신청 사유
	 * @nullable
	 */
	reason?: string | null;
	/** 신청 상태 */
	status: TenantAccessRequestStatus;
	/**
	 * 검토자 ID
	 * @nullable
	 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|[A-Za-z0-9_-]{22})$
	 */
	reviewerId?: string | null;
	/**
	 * 검토 코멘트
	 * @nullable
	 */
	reviewComment?: string | null;
	/**
	 * 검토 시각
	 * @nullable
	 */
	reviewedAt: string | null;
	/**
	 * 승인 적용 Tenant ID
	 * @nullable
	 * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|[A-Za-z0-9_-]{22})$
	 */
	appliedTenantId?: string | null;
	requester?: UserDto;
	/** @nullable */
	reviewer?: TenantAccessRequestDtoReviewer;
	space?: SpaceDto;
	requestedRole?: RoleDto;
	/** @nullable */
	previousRole?: TenantAccessRequestDtoPreviousRole;
	/** @nullable */
	appliedTenant?: TenantAccessRequestDtoAppliedTenant;
}
