/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. Core API와 IDP 관리 API를 함께 제공합니다. 대부분의 엔드포인트는 인증이 필요합니다.

**인증 방법:**
1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateOidcClientDtoLoginUi } from './updateOidcClientDtoLoginUi';

export interface UpdateOidcClientDto {
  /** 클라이언트 시크릿 */
  clientSecret?: string;
  /**
   * 클라이언트 이름
   * @maxLength 128
   */
  name?: string;
  /** 리다이렉트 URI 목록 */
  redirectUris?: string[];
  /** 로그인 화면 URL */
  loginUrl?: string;
  /** 인증 성공 후 기본 복귀 URL */
  defaultReturnTo?: string;
  /** 허용된 Grant 타입 */
  grantTypes?: string[];
  /** 응답 타입 */
  responseTypes?: string[];
  /**
   * 토큰 엔드포인트 인증 방식
   * @maxLength 50
   */
  tokenEndpointAuthMethod?: string;
  /** 허용된 스코프 */
  scope?: string;
  /** First-party 클라이언트 여부 */
  isFirstParty?: boolean;
  /**
   * 로그인 화면 표시 설정
   * @nullable
   */
  loginUi?: UpdateOidcClientDtoLoginUi;
  /** 로고 URI */
  logoUri?: string;
  /** 정책 URI */
  policyUri?: string;
  /** 서비스 약관 URI */
  tosUri?: string;
  /** 권한 동의 화면 생략 여부 */
  skipConsent?: boolean;
}
