import { MASKING_PRESETS } from "@cocrepo/constant";

/**
 * CASL masking action 이름을 persisted masking preset id로 매핑합니다.
 */
export const MASKING_ACTION_PRESET_MAP: Record<string, string> = {
	"READ:MASKED:EMAIL": MASKING_PRESETS.EMAIL,
	"READ:MASKED:PHONE": MASKING_PRESETS.PHONE,
	"READ:MASKED:NAME": MASKING_PRESETS.NAME,
	"READ:MASKED:SSN": MASKING_PRESETS.SSN,
	"READ:MASKED:CARD": MASKING_PRESETS.CARD,
	"READ:MASKED:ACCOUNT": MASKING_PRESETS.ACCOUNT,
};
