/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Plate
 * API 문서입니다. 대부분의 엔드포인트는 쿠키 기반 JWT 인증이 필요합니다. (@Public 데코레이터가 있는 엔드포인트는 예외)
 * OpenAPI spec version: 1.0.0
 */

import type { SortOrder } from "./sortOrder";
import type { UserSortField } from "./userSortField";
import type { UserStatus } from "./userStatus";

export type GetUsersParams = {
	/**
	 * @minimum 1
	 */
	skip?: number;
	/**
	 * @minimum 1
	 * @maximum 50
	 */
	take?: number;
	/**
	 * 통합 검색어 (이름, 이메일, 전화번호, 닉네임)
	 */
	search?: string;
	/**
	 * 역할 필터 (복수 선택 가능)
	 */
	roles?: string[];
	/**
	 * 상태 필터 (active, inactive, removed)
	 */
	status?: UserStatus;
	/**
	 * 분류 카테고리 ID
	 */
	categoryId?: string;
	/**
	 * 그룹 ID 목록 (복수 선택 가능)
	 */
	groupIds?: string[];
	/**
	 * 가입일 시작 (ISO8601)
	 */
	createdFrom?: string;
	/**
	 * 가입일 종료 (ISO8601)
	 */
	createdTo?: string;
	/**
	 * 정렬 기준 필드
	 */
	sortBy?: UserSortField;
	/**
	 * 정렬 순서 (asc, desc)
	 */
	sortOrder?: SortOrder;
	/**
	 * 페이지 번호
	 * @minimum 1
	 */
	page?: number;
	/**
	 * 페이지 크기
	 * @minimum 1
	 * @maximum 100
	 */
	limit?: number;
};
