/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Plate
 * API 문서입니다. 대부분의 엔드포인트는 쿠키 기반 JWT 인증이 필요합니다. (@Public 데코레이터가 있는 엔드포인트는 예외)
 * OpenAPI spec version: 1.0.0
 */

import type { RoleAssociationDto } from "./roleAssociationDto";
import type { RoleDtoClassification } from "./roleDtoClassification";
import type { Roles } from "./roles";

export interface RoleDto {
	id: string;
	seq: number;
	createdAt: string;
	updatedAt: string;
	/** @nullable */
	removedAt: string | null;
	name: Roles;
	/** @nullable */
	classification: RoleDtoClassification;
	/** @nullable */
	associations: RoleAssociationDto[] | null;
}
