import type { Meta, StoryObj } from "@storybook/react";
import { AdminTimelinesTimelineIdSessionsSessionIdPage } from "./AdminTimelinesTimelineIdSessionsSessionIdPage";

const defaultArgs = {
  "deleteProgramTargetName": "샘플 delete program target name 1",
  "descriptionText": "스토리북에서 확인할 description text 예시입니다.",
  "isDeleteProgramModalOpen": false,
  "isDeleteProgramPending": false,
  "isDeleteSessionModalOpen": false,
  "isDeleteSessionPending": false,
  "onClickCreateProgramButton": (..._args: never[]) => undefined,
  "onClickDeleteProgramButton": (..._args: never[]) => undefined,
  "onClickDeleteProgramCancelButton": (..._args: never[]) => undefined,
  "onClickDeleteProgramConfirmButton": (..._args: never[]) => undefined,
  "onClickDeleteSessionButton": (..._args: never[]) => undefined,
  "onClickDeleteSessionCancelButton": (..._args: never[]) => undefined,
  "onClickDeleteSessionConfirmButton": (..._args: never[]) => undefined,
  "onClickEditButton": (..._args: never[]) => undefined,
  "onClickEditProgramButton": (..._args: never[]) => undefined,
  "programs": [{
  "activityCountLabel": "샘플 activity count label 1",
  "capacityLabel": "샘플 capacity label 1",
  "href": {
  "anchor": (..._args: never[]) => undefined,
  "at": (..._args: never[]) => undefined,
  "big": (..._args: never[]) => undefined,
  "blink": (..._args: never[]) => undefined,
  "bold": (..._args: never[]) => undefined,
  "charAt": (..._args: never[]) => undefined,
  "charCodeAt": (..._args: never[]) => undefined,
  "codePointAt": (..._args: never[]) => undefined,
  "concat": (..._args: never[]) => undefined,
  "endsWith": (..._args: never[]) => undefined,
  "fixed": (..._args: never[]) => undefined,
  "fontcolor": (..._args: never[]) => undefined,
  "fontsize": (..._args: never[]) => undefined,
  "includes": (..._args: never[]) => undefined,
  "indexOf": (..._args: never[]) => undefined,
  "isWellFormed": (..._args: never[]) => undefined,
  "italics": (..._args: never[]) => undefined,
  "lastIndexOf": (..._args: never[]) => undefined,
  "link": (..._args: never[]) => undefined,
  "localeCompare": (..._args: never[]) => undefined,
  "match": (..._args: never[]) => undefined,
  "matchAll": (..._args: never[]) => undefined,
  "normalize": (..._args: never[]) => undefined,
  "padEnd": (..._args: never[]) => undefined,
  "padStart": (..._args: never[]) => undefined,
  "repeat": (..._args: never[]) => undefined,
  "replace": (..._args: never[]) => undefined,
  "replaceAll": (..._args: never[]) => undefined,
  "search": "샘플",
  "slice": (..._args: never[]) => undefined,
  "small": (..._args: never[]) => undefined,
  "split": (..._args: never[]) => undefined,
  "startsWith": (..._args: never[]) => undefined,
  "strike": (..._args: never[]) => undefined,
  "sub": (..._args: never[]) => undefined,
  "substr": (..._args: never[]) => undefined,
  "substring": (..._args: never[]) => undefined,
  "sup": (..._args: never[]) => undefined,
  "toLocaleLowerCase": (..._args: never[]) => undefined,
  "toLocaleUpperCase": (..._args: never[]) => undefined,
  "toLowerCase": (..._args: never[]) => undefined,
  "toString": (..._args: never[]) => undefined,
  "toUpperCase": (..._args: never[]) => undefined,
  "toWellFormed": (..._args: never[]) => undefined,
  "trim": (..._args: never[]) => undefined,
  "trimEnd": (..._args: never[]) => undefined,
  "trimLeft": (..._args: never[]) => undefined,
  "trimRight": (..._args: never[]) => undefined,
  "trimStart": (..._args: never[]) => undefined,
  "valueOf": (..._args: never[]) => undefined,
},
  "id": "item-1",
  "instructorName": "샘플 instructor name 1",
  "isConnectionResolved": false,
  "levelLabel": "샘플 level label 1",
  "previewText": "preview-text-1",
  "routineName": "샘플 routine name 1",
}, {
  "activityCountLabel": "샘플 activity count label 1",
  "capacityLabel": "샘플 capacity label 1",
  "href": {
  "anchor": (..._args: never[]) => undefined,
  "at": (..._args: never[]) => undefined,
  "big": (..._args: never[]) => undefined,
  "blink": (..._args: never[]) => undefined,
  "bold": (..._args: never[]) => undefined,
  "charAt": (..._args: never[]) => undefined,
  "charCodeAt": (..._args: never[]) => undefined,
  "codePointAt": (..._args: never[]) => undefined,
  "concat": (..._args: never[]) => undefined,
  "endsWith": (..._args: never[]) => undefined,
  "fixed": (..._args: never[]) => undefined,
  "fontcolor": (..._args: never[]) => undefined,
  "fontsize": (..._args: never[]) => undefined,
  "includes": (..._args: never[]) => undefined,
  "indexOf": (..._args: never[]) => undefined,
  "isWellFormed": (..._args: never[]) => undefined,
  "italics": (..._args: never[]) => undefined,
  "lastIndexOf": (..._args: never[]) => undefined,
  "link": (..._args: never[]) => undefined,
  "localeCompare": (..._args: never[]) => undefined,
  "match": (..._args: never[]) => undefined,
  "matchAll": (..._args: never[]) => undefined,
  "normalize": (..._args: never[]) => undefined,
  "padEnd": (..._args: never[]) => undefined,
  "padStart": (..._args: never[]) => undefined,
  "repeat": (..._args: never[]) => undefined,
  "replace": (..._args: never[]) => undefined,
  "replaceAll": (..._args: never[]) => undefined,
  "search": "샘플",
  "slice": (..._args: never[]) => undefined,
  "small": (..._args: never[]) => undefined,
  "split": (..._args: never[]) => undefined,
  "startsWith": (..._args: never[]) => undefined,
  "strike": (..._args: never[]) => undefined,
  "sub": (..._args: never[]) => undefined,
  "substr": (..._args: never[]) => undefined,
  "substring": (..._args: never[]) => undefined,
  "sup": (..._args: never[]) => undefined,
  "toLocaleLowerCase": (..._args: never[]) => undefined,
  "toLocaleUpperCase": (..._args: never[]) => undefined,
  "toLowerCase": (..._args: never[]) => undefined,
  "toString": (..._args: never[]) => undefined,
  "toUpperCase": (..._args: never[]) => undefined,
  "toWellFormed": (..._args: never[]) => undefined,
  "trim": (..._args: never[]) => undefined,
  "trimEnd": (..._args: never[]) => undefined,
  "trimLeft": (..._args: never[]) => undefined,
  "trimRight": (..._args: never[]) => undefined,
  "trimStart": (..._args: never[]) => undefined,
  "valueOf": (..._args: never[]) => undefined,
},
  "id": "item-1",
  "instructorName": "샘플 instructor name 1",
  "isConnectionResolved": false,
  "levelLabel": "샘플 level label 1",
  "previewText": "preview-text-1",
  "routineName": "샘플 routine name 1",
}],
  "resolvedPrograms": 1,
  "session": {
  "createdAt": "2026-04-14T09:00:00.000Z",
  "description": "스토리북에서 확인할 description 예시입니다.",
  "endDateTime": "2026-04-14T09:00:00.000Z",
  "recurringDayLabel": "샘플 recurring day label 1",
  "repeatCycleLabel": "샘플 repeat cycle label 1",
  "startDateTime": "2026-04-14T09:00:00.000Z",
  "timelineHref": {
  "anchor": (..._args: never[]) => undefined,
  "at": (..._args: never[]) => undefined,
  "big": (..._args: never[]) => undefined,
  "blink": (..._args: never[]) => undefined,
  "bold": (..._args: never[]) => undefined,
  "charAt": (..._args: never[]) => undefined,
  "charCodeAt": (..._args: never[]) => undefined,
  "codePointAt": (..._args: never[]) => undefined,
  "concat": (..._args: never[]) => undefined,
  "endsWith": (..._args: never[]) => undefined,
  "fixed": (..._args: never[]) => undefined,
  "fontcolor": (..._args: never[]) => undefined,
  "fontsize": (..._args: never[]) => undefined,
  "includes": (..._args: never[]) => undefined,
  "indexOf": (..._args: never[]) => undefined,
  "isWellFormed": (..._args: never[]) => undefined,
  "italics": (..._args: never[]) => undefined,
  "lastIndexOf": (..._args: never[]) => undefined,
  "link": (..._args: never[]) => undefined,
  "localeCompare": (..._args: never[]) => undefined,
  "match": (..._args: never[]) => undefined,
  "matchAll": (..._args: never[]) => undefined,
  "normalize": (..._args: never[]) => undefined,
  "padEnd": (..._args: never[]) => undefined,
  "padStart": (..._args: never[]) => undefined,
  "repeat": (..._args: never[]) => undefined,
  "replace": (..._args: never[]) => undefined,
  "replaceAll": (..._args: never[]) => undefined,
  "search": "샘플",
  "slice": (..._args: never[]) => undefined,
  "small": (..._args: never[]) => undefined,
  "split": (..._args: never[]) => undefined,
  "startsWith": (..._args: never[]) => undefined,
  "strike": (..._args: never[]) => undefined,
  "sub": (..._args: never[]) => undefined,
  "substr": (..._args: never[]) => undefined,
  "substring": (..._args: never[]) => undefined,
  "sup": (..._args: never[]) => undefined,
  "toLocaleLowerCase": (..._args: never[]) => undefined,
  "toLocaleUpperCase": (..._args: never[]) => undefined,
  "toLowerCase": (..._args: never[]) => undefined,
  "toString": (..._args: never[]) => undefined,
  "toUpperCase": (..._args: never[]) => undefined,
  "toWellFormed": (..._args: never[]) => undefined,
  "trim": (..._args: never[]) => undefined,
  "trimEnd": (..._args: never[]) => undefined,
  "trimLeft": (..._args: never[]) => undefined,
  "trimRight": (..._args: never[]) => undefined,
  "trimStart": (..._args: never[]) => undefined,
  "valueOf": (..._args: never[]) => undefined,
},
  "timelineName": "2026-04-14T09:00:00.000Z",
  "type": "샘플 type 1",
  "typeColor": "primary",
  "typeLabel": "샘플 type label 1",
},
  "title": "샘플 title",
  "totalPrograms": 12,
  "unresolvedPrograms": 1,
};

const emptyStateArgs = {
  ...defaultArgs,
  "programs": [],
};

const meta = {
  component: AdminTimelinesTimelineIdSessionsSessionIdPage,
  parameters: {
    layout: "fullscreen",
  },
  tags: ["autodocs"],
  args: defaultArgs as never,
} satisfies Meta<typeof AdminTimelinesTimelineIdSessionsSessionIdPage>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Default: Story = {};

export const EmptyState: Story = {
  args: emptyStateArgs as never,
};
