/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Core API
 * API 문서입니다. Core API와 IDP 관리 API를 함께 제공합니다. 대부분의 엔드포인트는 인증이 필요합니다.
 *
 * **인증 방법:**
 * 1. OAuth2 (권장) - Authorize 버튼 클릭 후 OIDC 로그인
 * 2. Cookie - 브라우저에서 로그인 후 쿠키 자동 전송
 *
 * **Tenant Scope:**
 * - 보호 API는 `x-tenant-id` header로 현재 Tenant를 선택합니다.
 * - 서버는 Tenant에서 Space를 파생하고, 기본적으로 현재 Space와 모든 하위 Space category 리소스를 조회합니다.
 * - `@WithAncestorSpaces`/`@WithSpaceTree`가 적용된 API는 Swagger JSON의 `x-space-resource-scope` 확장 필드로 scope를 표시합니다.
 * OpenAPI spec version: 1.0.0
 */

import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	InfiniteData,
	MutationFunction,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseMutationOptions,
	UseMutationResult,
	UseQueryOptions,
	UseQueryResult,
	UseSuspenseInfiniteQueryOptions,
	UseSuspenseInfiniteQueryResult,
	UseSuspenseQueryOptions,
	UseSuspenseQueryResult,
} from "@tanstack/react-query";
import {
	useMutation,
	useQuery,
	useSuspenseInfiniteQuery,
	useSuspenseQuery,
} from "@tanstack/react-query";
import type { BodyType, ErrorType } from "../../libs/customAxios";

import { customInstance } from "../../libs/customAxios";
import type {
	CreateFolder201,
	CreateFolderDto,
	GetFolders200,
	GetFoldersParams,
	UpdateFolder200,
	UpdateFolderDto,
} from "../model";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
	query: T,
	queryKey: K,
): T & { queryKey: K } => {
	const result = { queryKey } as T & { queryKey: K };
	for (const key of Object.keys(query)) {
		// The explicit queryKey always wins, matching the previous
		// `{ ...query, queryKey }` spread where it was set last.
		if (key === "queryKey") continue;
		Object.defineProperty(result, key, {
			enumerable: true,
			configurable: true,
			get: () => (query as Record<string, unknown>)[key],
		});
	}
	return result;
};

/**
 * 현재 선택한 Space의 폴더 목록을 조회합니다. 이름, 부모 폴더, 삭제 상태 필터를 지원합니다.
 * @summary 폴더 목록 조회
 */
export const getFolders = (
	params?: GetFoldersParams,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<GetFolders200>(
		{ url: `/api/v1/folders`, method: "GET", params, signal },
		options,
	);
};

export const getGetFoldersQueryKey = (params?: GetFoldersParams) => {
	return [`/api/v1/folders`, ...(params ? [params] : [])] as const;
};

export const getGetFoldersInfiniteQueryKey = (params?: GetFoldersParams) => {
	return ["infinite", `/api/v1/folders`, ...(params ? [params] : [])] as const;
};

export const getGetFoldersQueryOptions = <
	TData = Awaited<ReturnType<typeof getFolders>>,
	TError = ErrorType<void>,
>(
	params?: GetFoldersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetFoldersQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getFolders>>> = ({
		signal,
	}) => getFolders(params, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getFolders>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFoldersQueryResult = NonNullable<
	Awaited<ReturnType<typeof getFolders>>
>;
export type GetFoldersQueryError = ErrorType<void>;

export function useGetFolders<
	TData = Awaited<ReturnType<typeof getFolders>>,
	TError = ErrorType<void>,
>(
	params: undefined | GetFoldersParams,
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getFolders>>,
					TError,
					Awaited<ReturnType<typeof getFolders>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFolders<
	TData = Awaited<ReturnType<typeof getFolders>>,
	TError = ErrorType<void>,
>(
	params?: GetFoldersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getFolders>>,
					TError,
					Awaited<ReturnType<typeof getFolders>>
				>,
				"initialData"
			>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFolders<
	TData = Awaited<ReturnType<typeof getFolders>>,
	TError = ErrorType<void>,
>(
	params?: GetFoldersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 폴더 목록 조회
 */

export function useGetFolders<
	TData = Awaited<ReturnType<typeof getFolders>>,
	TError = ErrorType<void>,
>(
	params?: GetFoldersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetFoldersQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 폴더 목록 조회
 */
export const prefetchGetFoldersQuery = async <
	TData = Awaited<ReturnType<typeof getFolders>>,
	TError = ErrorType<void>,
>(
	queryClient: QueryClient,
	params?: GetFoldersParams,
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof getFolders>>, TError, TData>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
): Promise<QueryClient> => {
	const queryOptions = getGetFoldersQueryOptions(params, options);

	await queryClient.prefetchQuery(queryOptions);

	return queryClient;
};

export const getGetFoldersSuspenseQueryOptions = <
	TData = Awaited<ReturnType<typeof getFolders>>,
	TError = ErrorType<void>,
>(
	params?: GetFoldersParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getFolders>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetFoldersQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getFolders>>> = ({
		signal,
	}) => getFolders(params, requestOptions, signal);

	return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
		Awaited<ReturnType<typeof getFolders>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFoldersSuspenseQueryResult = NonNullable<
	Awaited<ReturnType<typeof getFolders>>
>;
export type GetFoldersSuspenseQueryError = ErrorType<void>;

export function useGetFoldersSuspense<
	TData = Awaited<ReturnType<typeof getFolders>>,
	TError = ErrorType<void>,
>(
	params: undefined | GetFoldersParams,
	options: {
		query: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getFolders>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFoldersSuspense<
	TData = Awaited<ReturnType<typeof getFolders>>,
	TError = ErrorType<void>,
>(
	params?: GetFoldersParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getFolders>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFoldersSuspense<
	TData = Awaited<ReturnType<typeof getFolders>>,
	TError = ErrorType<void>,
>(
	params?: GetFoldersParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getFolders>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 폴더 목록 조회
 */

export function useGetFoldersSuspense<
	TData = Awaited<ReturnType<typeof getFolders>>,
	TError = ErrorType<void>,
>(
	params?: GetFoldersParams,
	options?: {
		query?: Partial<
			UseSuspenseQueryOptions<
				Awaited<ReturnType<typeof getFolders>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetFoldersSuspenseQueryOptions(params, options);

	const query = useSuspenseQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

export const getGetFoldersSuspenseInfiniteQueryOptions = <
	TData = InfiniteData<Awaited<ReturnType<typeof getFolders>>>,
	TError = ErrorType<void>,
>(
	params?: GetFoldersParams,
	options?: {
		query?: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getFolders>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
) => {
	const { query: queryOptions, request: requestOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetFoldersInfiniteQueryKey(params);

	const queryFn: QueryFunction<Awaited<ReturnType<typeof getFolders>>> = ({
		signal,
	}) => getFolders(params, requestOptions, signal);

	return {
		queryKey,
		queryFn,
		...queryOptions,
	} as UseSuspenseInfiniteQueryOptions<
		Awaited<ReturnType<typeof getFolders>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFoldersSuspenseInfiniteQueryResult = NonNullable<
	Awaited<ReturnType<typeof getFolders>>
>;
export type GetFoldersSuspenseInfiniteQueryError = ErrorType<void>;

export function useGetFoldersSuspenseInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getFolders>>>,
	TError = ErrorType<void>,
>(
	params: undefined | GetFoldersParams,
	options: {
		query: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getFolders>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFoldersSuspenseInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getFolders>>>,
	TError = ErrorType<void>,
>(
	params?: GetFoldersParams,
	options?: {
		query?: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getFolders>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFoldersSuspenseInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getFolders>>>,
	TError = ErrorType<void>,
>(
	params?: GetFoldersParams,
	options?: {
		query?: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getFolders>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 폴더 목록 조회
 */

export function useGetFoldersSuspenseInfinite<
	TData = InfiniteData<Awaited<ReturnType<typeof getFolders>>>,
	TError = ErrorType<void>,
>(
	params?: GetFoldersParams,
	options?: {
		query?: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getFolders>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseSuspenseInfiniteQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetFoldersSuspenseInfiniteQueryOptions(
		params,
		options,
	);

	const query = useSuspenseInfiniteQuery(
		queryOptions,
		queryClient,
	) as UseSuspenseInfiniteQueryResult<TData, TError> & {
		queryKey: DataTag<QueryKey, TData, TError>;
	};

	return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 폴더 목록 조회
 */
export const prefetchGetFoldersInfiniteQuery = async <
	TData = Awaited<ReturnType<typeof getFolders>>,
	TError = ErrorType<void>,
>(
	queryClient: QueryClient,
	params?: GetFoldersParams,
	options?: {
		query?: Partial<
			UseSuspenseInfiniteQueryOptions<
				Awaited<ReturnType<typeof getFolders>>,
				TError,
				TData
			>
		>;
		request?: SecondParameter<typeof customInstance>;
	},
): Promise<QueryClient> => {
	const queryOptions = getGetFoldersSuspenseInfiniteQueryOptions(
		params,
		options,
	);

	await queryClient.prefetchInfiniteQuery(queryOptions);

	return queryClient;
};

/**
 * 현재 선택한 Space 아래에 새 폴더를 생성합니다. parentFolderId를 지정하면 하위 폴더로 생성합니다.
 * @summary 폴더 생성
 */
export const createFolder = (
	createFolderDto: BodyType<CreateFolderDto>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<CreateFolder201>(
		{
			url: `/api/v1/folders`,
			method: "POST",
			headers: { "Content-Type": "application/json" },
			data: createFolderDto,
			signal,
		},
		options,
	);
};

export const getCreateFolderMutationKey = () => ["createFolder"] as const;

export const getCreateFolderMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof createFolder>>,
		TError,
		CreateFolderMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof createFolder>>,
	TError,
	CreateFolderMutationVariables,
	TContext
> => {
	const mutationKey = getCreateFolderMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof createFolder>>,
		CreateFolderMutationVariables
	> = (props) => {
		const { data } = props ?? {};

		return createFolder(data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type CreateFolderMutationResult = NonNullable<
	Awaited<ReturnType<typeof createFolder>>
>;
export type CreateFolderMutationBody = BodyType<CreateFolderDto>;
export type CreateFolderMutationError = ErrorType<void>;
export type CreateFolderMutationVariables = { data: BodyType<CreateFolderDto> };

/**
 * @summary 폴더 생성
 */
export const useCreateFolder = <TError = ErrorType<void>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof createFolder>>,
			TError,
			CreateFolderMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof createFolder>>,
	TError,
	CreateFolderMutationVariables,
	TContext
> => {
	return useMutation(getCreateFolderMutationOptions(options), queryClient);
};
/**
 * 현재 선택한 Space 안에서 폴더명 또는 상위 폴더를 수정합니다.
 * @summary 폴더 수정
 */
export const updateFolder = (
	folderId: string,
	updateFolderDto: BodyType<UpdateFolderDto>,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<UpdateFolder200>(
		{
			url: `/api/v1/folders/${folderId}`,
			method: "PATCH",
			headers: { "Content-Type": "application/json" },
			data: updateFolderDto,
			signal,
		},
		options,
	);
};

export const getUpdateFolderMutationKey = () => ["updateFolder"] as const;

export const getUpdateFolderMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof updateFolder>>,
		TError,
		UpdateFolderMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof updateFolder>>,
	TError,
	UpdateFolderMutationVariables,
	TContext
> => {
	const mutationKey = getUpdateFolderMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof updateFolder>>,
		UpdateFolderMutationVariables
	> = (props) => {
		const { folderId, data } = props ?? {};

		return updateFolder(folderId, data, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type UpdateFolderMutationResult = NonNullable<
	Awaited<ReturnType<typeof updateFolder>>
>;
export type UpdateFolderMutationBody = BodyType<UpdateFolderDto>;
export type UpdateFolderMutationError = ErrorType<void>;
export type UpdateFolderMutationVariables = {
	folderId: string;
	data: BodyType<UpdateFolderDto>;
};

/**
 * @summary 폴더 수정
 */
export const useUpdateFolder = <TError = ErrorType<void>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof updateFolder>>,
			TError,
			UpdateFolderMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof updateFolder>>,
	TError,
	UpdateFolderMutationVariables,
	TContext
> => {
	return useMutation(getUpdateFolderMutationOptions(options), queryClient);
};
/**
 * 현재 선택한 Space 안에서 하위 폴더와 에셋이 없는 폴더를 삭제합니다.
 * @summary 폴더 삭제
 */
export const deleteFolder = (
	folderId: string,
	options?: SecondParameter<typeof customInstance>,
	signal?: AbortSignal,
) => {
	return customInstance<unknown>(
		{ url: `/api/v1/folders/${folderId}`, method: "DELETE", signal },
		options,
	);
};

export const getDeleteFolderMutationKey = () => ["deleteFolder"] as const;

export const getDeleteFolderMutationOptions = <
	TError = ErrorType<void>,
	TContext = unknown,
>(options?: {
	mutation?: UseMutationOptions<
		Awaited<ReturnType<typeof deleteFolder>>,
		TError,
		DeleteFolderMutationVariables,
		TContext
	>;
	request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
	Awaited<ReturnType<typeof deleteFolder>>,
	TError,
	DeleteFolderMutationVariables,
	TContext
> => {
	const mutationKey = getDeleteFolderMutationKey();
	const { mutation: mutationOptions, request: requestOptions } = options
		? options.mutation &&
			"mutationKey" in options.mutation &&
			options.mutation.mutationKey
			? options
			: { ...options, mutation: { ...options.mutation, mutationKey } }
		: { mutation: { mutationKey }, request: undefined };

	const mutationFn: MutationFunction<
		Awaited<ReturnType<typeof deleteFolder>>,
		DeleteFolderMutationVariables
	> = (props) => {
		const { folderId } = props ?? {};

		return deleteFolder(folderId, requestOptions);
	};

	return { mutationFn, ...mutationOptions };
};

export type DeleteFolderMutationResult = NonNullable<
	Awaited<ReturnType<typeof deleteFolder>>
>;

export type DeleteFolderMutationError = ErrorType<void>;
export type DeleteFolderMutationVariables = { folderId: string };

/**
 * @summary 폴더 삭제
 */
export const useDeleteFolder = <TError = ErrorType<void>, TContext = unknown>(
	options?: {
		mutation?: UseMutationOptions<
			Awaited<ReturnType<typeof deleteFolder>>,
			TError,
			DeleteFolderMutationVariables,
			TContext
		>;
		request?: SecondParameter<typeof customInstance>;
	},
	queryClient?: QueryClient,
): UseMutationResult<
	Awaited<ReturnType<typeof deleteFolder>>,
	TError,
	DeleteFolderMutationVariables,
	TContext
> => {
	return useMutation(getDeleteFolderMutationOptions(options), queryClient);
};
