export const EMAIL_VERIFICATION_ERROR = {
	ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
	INVALID_TOKEN: "EMAIL_VERIFICATION_INVALID",
	EXPIRED: "EMAIL_VERIFICATION_EXPIRED",
	ALREADY_VERIFIED: "EMAIL_VERIFICATION_ALREADY_VERIFIED",
	RESEND_COOLDOWN: "EMAIL_VERIFICATION_RESEND_COOLDOWN",
	SEND_FAILED: "EMAIL_VERIFICATION_SEND_FAILED",
} as const;
